// fish_db.js - Global & Australian Fish Species Predictive Database
window.FISH_DATABASE = [
    // Australian Freshwater & Saltwater Gamefish
    { name: "Rainbow Trout", waterType: "freshwater", category: "Trout / Salmonid" },
    { name: "Brown Trout", waterType: "freshwater", category: "Trout / Salmonid" },
    { name: "Brook Trout", waterType: "freshwater", category: "Trout / Salmonid" },
    { name: "Giant Trevally (GT)", waterType: "saltwater", category: "Pelagic / Flats Predator" },
    { name: "Golden Trevally", waterType: "saltwater", category: "Flats Predator" },
    { name: "Bluefin Trevally", waterType: "saltwater", category: "Reef / Flats Predator" },
    { name: "Queenfish", waterType: "saltwater", category: "Pelagic / Surface Striker" },
    { name: "Barramundi", waterType: "freshwater", category: "Estuary & Tropical Freshwater" },
    { name: "Coral Trout", waterType: "saltwater", category: "Reef Predator" },
    { name: "Dusky Flathead", waterType: "saltwater", category: "Estuary Bottom Predator" },
    { name: "Yellowfin Bream", waterType: "saltwater", category: "Estuary / Coastal" },
    { name: "Black Bream", waterType: "saltwater", category: "Estuary / River" },
    { name: "Snapper", waterType: "saltwater", category: "Inshore Reef / Bay" },
    { name: "Murray Cod", waterType: "freshwater", category: "Freshwater Apex Predator" },
    { name: "Australian Bass", waterType: "freshwater", category: "Freshwater River Sportfish" },
    { name: "Golden Perch (Yellowbelly)", waterType: "freshwater", category: "Freshwater Native" },
    { name: "Silver Perch", waterType: "freshwater", category: "Freshwater Native" },
    { name: "Australian Salmon", waterType: "saltwater", category: "Coastal Pelagic" },
    { name: "Luderick (Blackfish)", waterType: "saltwater", category: "Estuary & Rock Fishing" },
    { name: "King George Whiting", waterType: "saltwater", category: "Inshore / Bay" },
    { name: "Sand Whiting", waterType: "saltwater", category: "Beach / Estuary" },
    { name: "Mangrove Jack", waterType: "saltwater", category: "Estuary / Structure" },
    { name: "Spanish Mackerel", waterType: "saltwater", category: "Pelagic Speedster" },
    { name: "Yellowtail Kingfish", waterType: "saltwater", category: "Inshore / Offshore Reef" },
    { name: "Cobia", waterType: "saltwater", category: "Pelagic / Offshore" },
    { name: "Red Emperor", waterType: "saltwater", category: "Deep Reef" },
    { name: "Spangled Emperor", waterType: "saltwater", category: "Reef / Lagoon" },
    { name: "Bonefish", waterType: "saltwater", category: "Tropical Flats Speedster" },
    { name: "Tarpon", waterType: "saltwater", category: "Tropical Megalops / Estuary" },
    { name: "Permit", waterType: "saltwater", category: "Tropical Flats Gamefish" },
    { name: "Mahi Mahi (Dorado)", waterType: "saltwater", category: "Offshore Bluewater" },
    { name: "Southern Bluefin Tuna", waterType: "saltwater", category: "Offshore Pelagic" },
    { name: "Yellowfin Tuna", waterType: "saltwater", category: "Offshore Pelagic" },
    { name: "Longtail Tuna", waterType: "saltwater", category: "Inshore Pelagic" },
    { name: "Mackerel Tuna", waterType: "saltwater", category: "Inshore Pelagic" },
    { name: "Black Marlin", waterType: "saltwater", category: "Bluewater Billfish" },
    { name: "Blue Marlin", waterType: "saltwater", category: "Bluewater Billfish" },
    { name: "Sailfish", waterType: "saltwater", category: "Bluewater Billfish" },

    // Global Freshwater & Saltwater Fly Fishing Species
    { name: "Striped Bass", waterType: "saltwater", category: "Coastal Anadromous" },
    { name: "Largemouth Bass", waterType: "freshwater", category: "Freshwater Gamefish" },
    { name: "Smallmouth Bass", waterType: "freshwater", category: "Freshwater River Bass" },
    { name: "Peacock Bass", waterType: "freshwater", category: "Tropical Predator" },
    { name: "Steelhead Trout", waterType: "freshwater", category: "Anadromous Rainbow" },
    { name: "Atlantic Salmon", waterType: "freshwater", category: "Anadromous Salmonid" },
    { name: "Chinook Salmon (King)", waterType: "freshwater", category: "Pacific Salmon" },
    { name: "Coho Salmon (Silver)", waterType: "freshwater", category: "Pacific Salmon" },
    { name: "Sockeye Salmon", waterType: "freshwater", category: "Pacific Salmon" },
    { name: "Northern Pike", waterType: "freshwater", category: "Freshwater Predator" },
    { name: "Muskellunge (Musky)", waterType: "freshwater", category: "Freshwater Apex Predator" },
    { name: "Arctic Char", waterType: "freshwater", category: "Coldwater Salmonid" },
    { name: "Cutthroat Trout", waterType: "freshwater", category: "Mountain Trout" },
    { name: "Bull Trout", waterType: "freshwater", category: "Coldwater Char" },
    { name: "Redfish (Red Drum)", waterType: "saltwater", category: "Shallow Marsh & Flats" },
    { name: "Snook", waterType: "saltwater", category: "Mangrove & Inshore" },
    { name: "Roosterfish", waterType: "saltwater", category: "Pacific Surf Predator" },
    { name: "Golden Dorado", waterType: "freshwater", category: "South American River King" },
    { name: "Tigerfish", waterType: "freshwater", category: "African River Apex" }
];
