// fish_db.js - Official Australian & Global Fish Species Database (NSW DPIRD & National Alignment)
window.FISH_DATABASE = [
    // =========================================================================
    // 🌲 FRESHWATER SPECIES (NSW DPIRD & NATIONAL)
    // =========================================================================
    { name: "Rainbow Trout", sciName: "Oncorhynchus mykiss", waterType: "freshwater", category: "Trout / Salmonid", image: "images/dpi_illustrations/rainbow_trout.jpg" },
    { name: "Brown Trout", sciName: "Salmo trutta", waterType: "freshwater", category: "Trout / Salmonid", image: "images/dpi_illustrations/brown_trout.jpg" },
    { name: "Brook Trout", sciName: "Salvelinus fontinalis", waterType: "freshwater", category: "Trout / Salmonid", image: "images/dpi_illustrations/brook_trout.jpg" },
    { name: "Steelhead Trout", sciName: "Oncorhynchus mykiss", waterType: "freshwater", category: "Anadromous Rainbow", image: "images/dpi_illustrations/rainbow_trout.jpg" },
    { name: "Atlantic Salmon", sciName: "Salmo salar", waterType: "freshwater", category: "Anadromous Salmonid", image: "images/dpi_illustrations/atlantic_salmon.jpg" },
    { name: "Murray Cod", sciName: "Maccullochella peelii", waterType: "freshwater", category: "Freshwater Apex Predator", image: "images/dpi_illustrations/murray_cod.jpg" },
    { name: "Trout Cod", sciName: "Maccullochella macquariensis", waterType: "freshwater", category: "Protected Native", image: "images/dpi_illustrations/trout_cod.jpg" },
    { name: "Eastern Freshwater Cod", sciName: "Maccullochella ikei", waterType: "freshwater", category: "Protected Native", image: "images/dpi_illustrations/eastern_freshwater_cod.jpg" },
    { name: "Mary River Cod", sciName: "Maccullochella mariensis", waterType: "freshwater", category: "Protected Native", image: "images/dpi_illustrations/mary_river_cod.jpg" },
    { name: "Macquarie Perch", sciName: "Macquaria australasica", waterType: "freshwater", category: "Protected Native Perch", image: "images/dpi_illustrations/macquarie_perch.jpg" },
    { name: "Australian Bass", sciName: "Macquaria novemaculeata", waterType: "freshwater", category: "Freshwater River Sportfish", image: "images/dpi_illustrations/australian_bass.jpg" },
    { name: "Estuary Perch", sciName: "Macquaria colonorum", waterType: "freshwater", category: "Estuary Sportfish", image: "images/dpi_illustrations/estuary_perch.jpg" },
    { name: "Silver Perch", sciName: "Bidyanus bidyanus", waterType: "freshwater", category: "Freshwater Native", image: "images/dpi_illustrations/silver_perch.jpg" },
    { name: "Golden Perch (Yellowbelly)", sciName: "Macquaria ambigua", waterType: "freshwater", category: "Freshwater Native", image: "images/dpi_illustrations/golden_perch.jpg" },
    { name: "Golden Perch", sciName: "Macquaria ambigua", waterType: "freshwater", category: "Freshwater Native", image: "images/dpi_illustrations/golden_perch.jpg" },
    { name: "Freshwater Catfish (Eel-tailed Catfish)", sciName: "Tandanus tandanus", waterType: "freshwater", category: "Freshwater Native", image: "images/dpi_illustrations/golden_perch.jpg" },
    { name: "River Blackfish", sciName: "Gadopsis marmoratus", waterType: "freshwater", category: "Freshwater Native", image: "images/dpi_illustrations/australian_bass.jpg" },
    { name: "Two-spined Blackfish", sciName: "Gadopsis bispinosus", waterType: "freshwater", category: "Highland Native", image: "images/dpi_illustrations/australian_bass.jpg" },
    { name: "Spangled Perch", sciName: "Leiopotherapon unicolor", waterType: "freshwater", category: "Inland Native", image: "images/dpi_illustrations/silver_perch.jpg" },
    { name: "Bony Bream (Pyramid Bream)", sciName: "Nematalosa erebi", waterType: "freshwater", category: "Native Forage Fish", image: "images/dpi_illustrations/silver_perch.jpg" },
    { name: "Long-finned Eel", sciName: "Anguilla reinhardtii", waterType: "freshwater", category: "Freshwater / Estuary Native", image: "images/dpi_illustrations/garfish.jpg" },
    { name: "Short-finned Eel", sciName: "Anguilla australis", waterType: "freshwater", category: "Freshwater / Estuary Native", image: "images/dpi_illustrations/garfish.jpg" },
    { name: "Southern Purple-Spotted Gudgeon", sciName: "Mogurnda adspersa", waterType: "freshwater", category: "Protected Native", image: "images/dpi_illustrations/macquarie_perch.jpg" },
    { name: "Olive Perchlet", sciName: "Ambassis agassizii", waterType: "freshwater", category: "Protected Native", image: "images/dpi_illustrations/macquarie_perch.jpg" },
    { name: "Southern Pygmy Perch", sciName: "Nannoperca australis", waterType: "freshwater", category: "Protected Native", image: "images/dpi_illustrations/macquarie_perch.jpg" },
    { name: "Murray Hardyhead", sciName: "Craterocephalus fluviatilis", waterType: "freshwater", category: "Protected Native", image: "images/dpi_illustrations/macquarie_perch.jpg" },
    { name: "Australian Smelt", sciName: "Retropinna semoni", waterType: "freshwater", category: "Native Forage Fish", image: "images/dpi_illustrations/garfish.jpg" },
    { name: "Barramundi", sciName: "Lates calcarifer", waterType: "freshwater", category: "Estuary & Tropical Freshwater", image: "images/dpi_illustrations/barramundi.jpg" },
    { name: "Sooty Grunter", sciName: "Hephaestus fuliginosus", waterType: "freshwater", category: "Northern Freshwater Sportfish", image: "images/dpi_illustrations/sooty_grunter.jpg" },
    { name: "Saratoga", sciName: "Scleropages leichardti", waterType: "freshwater", category: "Ancient Freshwater Native", image: "images/dpi_illustrations/saratoga.jpg" },
    { name: "Redfin Perch", sciName: "Perca fluviatilis", waterType: "freshwater", category: "Declared Pest Species", image: "images/dpi_illustrations/redfin_perch.jpg" },
    { name: "European Carp", sciName: "Cyprinus carpio", waterType: "freshwater", category: "Noxious Pest Species", image: "images/dpi_illustrations/european_carp.jpg" },
    { name: "Eastern Mosquitofish (Gambusia)", sciName: "Gambusia holbrooki", waterType: "freshwater", category: "Noxious Pest Species", image: "images/dpi_illustrations/european_carp.jpg" },
    { name: "Goldfish", sciName: "Carassius auratus", waterType: "freshwater", category: "Declared Pest Species", image: "images/dpi_illustrations/european_carp.jpg" },
    { name: "Oriental Weatherloach", sciName: "Misgurnus anguillicaudatus", waterType: "freshwater", category: "Noxious Pest Species", image: "images/dpi_illustrations/european_carp.jpg" },
    { name: "Tilapia", sciName: "Oreochromis mossambicus", waterType: "freshwater", category: "Declared Pest Species", image: "images/dpi_illustrations/tilapia.jpg" },

    // =========================================================================
    // 🌊 SALTWATER, ESTUARY, REEF & PELAGIC SPECIES (NSW DPIRD & NATIONAL)
    // =========================================================================
    { name: "Dusky Flathead", sciName: "Platycephalus fuscus", waterType: "saltwater", category: "Estuary Bottom Predator", image: "images/dpi_illustrations/dusky_flathead.jpg" },
    { name: "Sand Flathead", sciName: "Platycephalus bassensis", waterType: "saltwater", category: "Estuary / Coastal", image: "images/dpi_illustrations/sand_flathead.jpg" },
    { name: "Tiger Flathead", sciName: "Platycephalus richardsoni", waterType: "saltwater", category: "Offshore Coastal Flathead", image: "images/dpi_illustrations/sand_flathead.jpg" },
    { name: "Bluespotted Flathead", sciName: "Platycephalus caeruleopunctatus", waterType: "saltwater", category: "Estuary / Coastal", image: "images/dpi_illustrations/flathead_bluespotted.jpg" },
    { name: "Flathead (Blue-spotted/Southern)", sciName: "Platycephalus caeruleopunctatus", waterType: "saltwater", category: "Estuary / Coastal", image: "images/dpi_illustrations/flathead_bluespotted.jpg" },
    { name: "Yellowfin Bream", sciName: "Acanthopagrus australis", waterType: "saltwater", category: "Estuary / Coastal", image: "images/dpi_illustrations/yellowfin_bream.jpg" },
    { name: "Black Bream", sciName: "Acanthopagrus butcheri", waterType: "saltwater", category: "Estuary / River", image: "images/dpi_illustrations/black_bream.jpg" },
    { name: "Bream (Black)", sciName: "Acanthopagrus butcheri", waterType: "saltwater", category: "Estuary / River", image: "images/dpi_illustrations/black_bream.jpg" },
    { name: "Tarwhine", sciName: "Rhabdosargus sarba", waterType: "saltwater", category: "Estuary / Coastal", image: "images/dpi_illustrations/tarwhine.jpg" },
    { name: "Snapper", sciName: "Chrysophrys auratus", waterType: "saltwater", category: "Inshore Reef / Bay", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Pink Snapper", sciName: "Chrysophrys auratus", waterType: "saltwater", category: "Inshore Reef / Bay", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Golden Snapper (Fingermark)", sciName: "Lutjanus johnii", waterType: "saltwater", category: "Tropical Estuary / Reef", image: "images/dpi_illustrations/golden_snapper.jpg" },
    { name: "Golden Snapper", sciName: "Lutjanus johnii", waterType: "saltwater", category: "Tropical Estuary / Reef", image: "images/dpi_illustrations/golden_snapper.jpg" },
    { name: "Moses Snapper (Moses Perch)", sciName: "Lutjanus russellii", waterType: "saltwater", category: "Inshore Reef", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Mangrove Jack", sciName: "Lutjanus argentimaculatus", waterType: "saltwater", category: "Estuary / Structure Predator", image: "images/dpi_illustrations/mangrove_jack.jpg" },
    { name: "Pearl Perch", sciName: "Glaucosoma scapulare", waterType: "saltwater", category: "Deep Offshore Reef", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Sand Whiting", sciName: "Sillago ciliata", waterType: "saltwater", category: "Beach / Estuary Flats", image: "images/dpi_illustrations/sand_whiting.jpg" },
    { name: "Trumpeter Whiting (Winter Whiting)", sciName: "Sillago maculata", waterType: "saltwater", category: "Bay / Estuary", image: "images/dpi_illustrations/sand_whiting.jpg" },
    { name: "King George Whiting", sciName: "Sillaginodes punctatus", waterType: "saltwater", category: "Inshore / Weed Beds", image: "images/dpi_illustrations/king_george_whiting.jpg" },
    { name: "Yellowfin Whiting", sciName: "Sillago schomburgkii", waterType: "saltwater", category: "Inshore / Bay", image: "images/dpi_illustrations/yellowfin_whiting.jpg" },
    { name: "Mulloway", sciName: "Argyrosomus japonicus", waterType: "saltwater", category: "Estuary & Coastal Apex", image: "images/dpi_illustrations/mulloway.jpg" },
    { name: "Mulloway (Jewfish)", sciName: "Argyrosomus japonicus", waterType: "saltwater", category: "Estuary & Coastal Apex", image: "images/dpi_illustrations/mulloway.jpg" },
    { name: "Teraglin", sciName: "Atractoscion aequidens", waterType: "saltwater", category: "Offshore Reef", image: "images/dpi_illustrations/mulloway.jpg" },
    { name: "Yellowtail Kingfish", sciName: "Seriola lalandi", waterType: "saltwater", category: "Inshore / Offshore Pelagic", image: "images/dpi_illustrations/yellowtail_kingfish.jpg" },
    { name: "Kingfish (Yellowtail)", sciName: "Seriola lalandi", waterType: "saltwater", category: "Inshore / Offshore Pelagic", image: "images/dpi_illustrations/yellowtail_kingfish.jpg" },
    { name: "Samsonfish", sciName: "Seriola hippos", waterType: "saltwater", category: "Offshore Reef Pelagic", image: "images/dpi_illustrations/yellowtail_kingfish.jpg" },
    { name: "Amberjack", sciName: "Seriola dumerili", waterType: "saltwater", category: "Offshore Reef Pelagic", image: "images/dpi_illustrations/yellowtail_kingfish.jpg" },
    { name: "Australian Salmon", sciName: "Arripis trutta", waterType: "saltwater", category: "Coastal Pelagic / Surf", image: "images/dpi_illustrations/australian_salmon.jpg" },
    { name: "Australian Salmon (Eastern Australian Salmon)", sciName: "Arripis trutta", waterType: "saltwater", category: "Coastal Pelagic / Surf", image: "images/dpi_illustrations/australian_salmon.jpg" },
    { name: "Salmon (Western Australian)", sciName: "Arripis truttaceus", waterType: "saltwater", category: "Coastal Pelagic", image: "images/dpi_illustrations/australian_salmon.jpg" },
    { name: "Tailor", sciName: "Pomatomus saltatrix", waterType: "saltwater", category: "Estuary & Surf Pelagic", image: "images/dpi_illustrations/tailor.jpg" },
    { name: "Luderick (Blackfish)", sciName: "Girella tricuspidata", waterType: "saltwater", category: "Estuary & Rock Fishing", image: "images/dpi_illustrations/luderick.jpg" },
    { name: "Luderick", sciName: "Girella tricuspidata", waterType: "saltwater", category: "Estuary & Rock Fishing", image: "images/dpi_illustrations/luderick.jpg" },
    { name: "Rock Blackfish (Black Drummer)", sciName: "Girella elevata", waterType: "saltwater", category: "Ocean Rock Wash", image: "images/dpi_illustrations/luderick.jpg" },
    { name: "Silver Drummer", sciName: "Kyphosus sydneyanus", waterType: "saltwater", category: "Ocean Rock Wash", image: "images/dpi_illustrations/luderick.jpg" },
    { name: "Blue Drummer", sciName: "Girella cyanea", waterType: "saltwater", category: "Offshore Islet Reef", image: "images/dpi_illustrations/luderick.jpg" },
    { name: "Silver Trevally", sciName: "Pseudocaranx georgianus", waterType: "saltwater", category: "Inshore / Estuary / Bay", image: "images/dpi_illustrations/silver_trevally.jpg" },
    { name: "Giant Trevally (GT)", sciName: "Caranx ignobilis", waterType: "saltwater", category: "Pelagic / Flats Predator", image: "images/dpi_illustrations/giant_trevally.jpg" },
    { name: "Giant Trevally", sciName: "Caranx ignobilis", waterType: "saltwater", category: "Pelagic / Flats Predator", image: "images/dpi_illustrations/giant_trevally.jpg" },
    { name: "Bigeye Trevally", sciName: "Caranx sexfasciatus", waterType: "saltwater", category: "Inshore / Estuary Pelagic", image: "images/dpi_illustrations/giant_trevally.jpg" },
    { name: "Golden Trevally", sciName: "Gnathanodon speciosus", waterType: "saltwater", category: "Flats Predator", image: "images/dpi_illustrations/giant_trevally.jpg" },
    { name: "Queenfish", sciName: "Scomberoides commersonnianus", waterType: "saltwater", category: "Tropical Pelagic", image: "images/dpi_illustrations/queenfish.jpg" },
    { name: "Mahi Mahi (Dorado)", sciName: "Coryphaena hippurus", waterType: "saltwater", category: "Offshore Bluewater", image: "images/dpi_illustrations/mahi_mahi.jpg" },
    { name: "Mahi Mahi (Dolphin Fish / Dorado)", sciName: "Coryphaena hippurus", waterType: "saltwater", category: "Offshore Bluewater", image: "images/dpi_illustrations/mahi_mahi.jpg" },
    { name: "Spanish Mackerel", sciName: "Scomberomorus commerson", waterType: "saltwater", category: "Pelagic Speedster", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Spotted Mackerel", sciName: "Scomberomorus munroi", waterType: "saltwater", category: "Inshore Pelagic", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "School Mackerel", sciName: "Scomberomorus queenslandicus", waterType: "saltwater", category: "Inshore Pelagic", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Wahoo", sciName: "Acanthocybium solandri", waterType: "saltwater", category: "Offshore Bluewater", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Cobia (Black Kingfish)", sciName: "Rachycentron canadum", waterType: "saltwater", category: "Inshore / Offshore Pelagic", image: "images/dpi_illustrations/yellowtail_kingfish.jpg" },
    { name: "Yellowfin Tuna", sciName: "Thunnus albacares", waterType: "saltwater", category: "Offshore Gamefish", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Southern Bluefin Tuna", sciName: "Thunnus maccoyii", waterType: "saltwater", category: "Offshore Gamefish", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Bigeye Tuna", sciName: "Thunnus obesus", waterType: "saltwater", category: "Offshore Gamefish", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Albacore Tuna", sciName: "Thunnus alalunga", waterType: "saltwater", category: "Offshore Gamefish", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Longtail Tuna (Northern Bluefin)", sciName: "Thunnus tonggol", waterType: "saltwater", category: "Inshore / Offshore Pelagic", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Skipjack Tuna (Striped Tuna)", sciName: "Katsuwonus pelamis", waterType: "saltwater", category: "Offshore Pelagic", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Mackerel Tuna (Little Tunny)", sciName: "Euthynnus affinis", waterType: "saltwater", category: "Inshore / Offshore Pelagic", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Australian Bonito", sciName: "Sarda australis", waterType: "saltwater", category: "Inshore Pelagic", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Striped Marlin", sciName: "Kajikia audax", waterType: "saltwater", category: "Offshore Billfish", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Blue Marlin", sciName: "Makaira nigricans", waterType: "saltwater", category: "Offshore Billfish", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Black Marlin", sciName: "Istiompax indica", waterType: "saltwater", category: "Offshore Billfish", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Sailfish", sciName: "Istiophorus platypterus", waterType: "saltwater", category: "Offshore Billfish", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Broadbill Swordfish", sciName: "Xiphias gladius", waterType: "saltwater", category: "Offshore Deep Billfish", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Shortbill Spearfish", sciName: "Tetrapturus angustirostris", waterType: "saltwater", category: "Offshore Billfish", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Eastern Blue Groper", sciName: "Achoerodus viridis", waterType: "saltwater", category: "Protected NSW State Fish", image: "images/dpi_illustrations/eastern_blue_groper.jpg" },
    { name: "Blue Morwong (Rubberlip Morwong)", sciName: "Nemadactylus douglasii", waterType: "saltwater", category: "Offshore Reef", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Grey Morwong (Jackass Fish)", sciName: "Nemadactylus macropterus", waterType: "saltwater", category: "Offshore Reef", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Red Morwong", sciName: "Cheilodactylus fuscus", waterType: "saltwater", category: "Inshore Reef / Kelp", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Bar Cod (Band-ed Rockcod)", sciName: "Epinephelus ergastularius", waterType: "saltwater", category: "Deep Sea Reef", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Bass Groper", sciName: "Polyprion americanus", waterType: "saltwater", category: "Deep Sea Reef", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Hapuku", sciName: "Polyprion oxygeneios", waterType: "saltwater", category: "Deep Sea Reef", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Blue-eye Trevalla", sciName: "Hyperoglyphe antarctica", waterType: "saltwater", category: "Deep Sea Continental Shelf", image: "images/dpi_illustrations/silver_trevally.jpg" },
    { name: "Gemfish", sciName: "Rexea solandri", waterType: "saltwater", category: "Deep Sea Pelagic", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Garfish", sciName: "Hyporhamphus australis", waterType: "saltwater", category: "Inshore / Bay", image: "images/dpi_illustrations/garfish.jpg" },
    { name: "Sea Garfish", sciName: "Hyporhamphus australis", waterType: "saltwater", category: "Inshore / Bay", image: "images/dpi_illustrations/garfish.jpg" },
    { name: "Sea Garfish (Eastern Sea Garfish)", sciName: "Hyporhamphus australis", waterType: "saltwater", category: "Inshore / Bay", image: "images/dpi_illustrations/garfish.jpg" },
    { name: "River Garfish", sciName: "Hyporhamphus regularis", waterType: "saltwater", category: "Estuary / River", image: "images/dpi_illustrations/garfish.jpg" },
    { name: "Yellowtail Scad (Yakker)", sciName: "Trachurus novaezelandiae", waterType: "saltwater", category: "Inshore Baitfish", image: "images/dpi_illustrations/silver_trevally.jpg" },
    { name: "Slimy Mackerel (Pacific Mackerel)", sciName: "Scomber australasicus", waterType: "saltwater", category: "Inshore / Offshore Baitfish", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Yellowfin Leatherjacket", sciName: "Meuschenia venusta", waterType: "saltwater", category: "Reef / Estuary", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Six-spined Leatherjacket", sciName: "Meuschenia freycineti", waterType: "saltwater", category: "Reef / Estuary", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Flounder (Greenback & Small-toothed)", sciName: "Rhombosolea tapirina", waterType: "saltwater", category: "Estuary Sandy Bottom", image: "images/dpi_illustrations/sand_flathead.jpg" },
    { name: "Sole (Black Sole / Many-banded Sole)", sciName: "Synaptura nigra", waterType: "saltwater", category: "Estuary Sandy Bottom", image: "images/dpi_illustrations/sand_flathead.jpg" },
    { name: "John Dory", sciName: "Zeus faber", waterType: "saltwater", category: "Deep Inshore / Harbour", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Mirror Dory", sciName: "Zenopsis nebulosa", waterType: "saltwater", category: "Offshore Deep Reef", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Silver Sweep", sciName: "Scorpis lineolata", waterType: "saltwater", category: "Coastal Wash / Reef", image: "images/dpi_illustrations/silver_trevally.jpg" },
    { name: "Red Gurnard", sciName: "Chelidonichthys kumu", waterType: "saltwater", category: "Sand / Mud Bottom", image: "images/dpi_illustrations/sand_flathead.jpg" },
    { name: "Sea Mullet (Bully Mullet)", sciName: "Mugil cephalus", waterType: "saltwater", category: "Estuary / Coastal Surf", image: "images/dpi_illustrations/australian_salmon.jpg" },
    { name: "Flat-tail Mullet / Sand Mullet", sciName: "Liza argentea", waterType: "saltwater", category: "Estuary / Tidal Creek", image: "images/dpi_illustrations/australian_salmon.jpg" },
    { name: "Sergeant Baker", sciName: "Latropiscis purpurissatus", waterType: "saltwater", category: "Ocean Reef Bottom", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Striped Trumpeter", sciName: "Latris lineata", waterType: "saltwater", category: "Deep Reef", image: "images/dpi_illustrations/striped_trumpeter.jpg" },
    { name: "Coral Trout", sciName: "Plectropomus leopardus", waterType: "saltwater", category: "Reef Predator", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Coral Trout (Bar-cheek & Leopard)", sciName: "Plectropomus leopardus", waterType: "saltwater", category: "Reef Predator", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Gummy Shark", sciName: "Mustelus antarcticus", waterType: "saltwater", category: "Inshore / Bay Shark", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "School Shark", sciName: "Galeorhinus galeus", waterType: "saltwater", category: "Coastal / Offshore Shark", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Mako Shark", sciName: "Isurus oxyrinchus", waterType: "saltwater", category: "Offshore Pelagic Shark", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Tiger Shark", sciName: "Galeocerdo cuvier", waterType: "saltwater", category: "Coastal Apex Shark", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Hammerhead Shark (Smooth)", sciName: "Sphyrna zygaena", waterType: "saltwater", category: "Inshore / Offshore Shark", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Great White Shark (White Pointer)", sciName: "Carcharodon carcharias", waterType: "saltwater", category: "Protected Apex Predator", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Grey Nurse Shark", sciName: "Carcharias taurus", waterType: "saltwater", category: "Critically Endangered Shark", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Scalloped Hammerhead Shark", sciName: "Sphyrna lewini", waterType: "saltwater", category: "Endangered Shark", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Great Hammerhead Shark", sciName: "Sphyrna mokarran", waterType: "saltwater", category: "Endangered Shark", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Black Rockcod", sciName: "Epinephelus daemelii", waterType: "saltwater", category: "Protected Coastal Groper", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Ballina Angelfish", sciName: "Chaetodontoplus ballinae", waterType: "saltwater", category: "Protected Marine Fish", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Weedy Seadragon", sciName: "Phyllopteryx taeniolatus", waterType: "saltwater", category: "Protected Syngnathid", image: "images/dpi_illustrations/garfish.jpg" },
    { name: "White's Seahorse (Sydney Seahorse)", sciName: "Hippocampus whitei", waterType: "saltwater", category: "Endangered Syngnathid", image: "images/dpi_illustrations/garfish.jpg" },

    // International & Tropical Flats Species
    { name: "Bonefish", sciName: "Albula vulpes", waterType: "saltwater", category: "Tropical Flats Speedster", image: "images/dpi_illustrations/sand_whiting.jpg" },
    { name: "Tarpon", sciName: "Megalops atlanticus", waterType: "saltwater", category: "Tropical Megalops / Estuary", image: "images/dpi_illustrations/barramundi.jpg" },
    { name: "Permit", sciName: "Trachinotus falcatus", waterType: "saltwater", category: "Tropical Flats Gamefish", image: "images/dpi_illustrations/silver_trevally.jpg" }
];
