// fish_db.js - Official Australian & Global Fish Species Database with Distinct DPIRD Scientific Cutouts
window.FISH_DATABASE = [
    // Freshwater Species
    { name: "Rainbow Trout", sciName: "Oncorhynchus mykiss", waterType: "freshwater", category: "Trout / Salmonid", image: "images/dpi_illustrations/rainbow_trout.jpg" },
    { name: "Brown Trout", sciName: "Salmo trutta", waterType: "freshwater", category: "Trout / Salmonid", image: "images/dpi_illustrations/brown_trout.jpg" },
    { name: "Brook Trout", sciName: "Salvelinus fontinalis", waterType: "freshwater", category: "Trout / Salmonid", image: "images/dpi_illustrations/brook_trout.jpg" },
    { name: "Steelhead Trout", sciName: "Oncorhynchus mykiss", waterType: "freshwater", category: "Anadromous Rainbow", image: "images/dpi_illustrations/rainbow_trout.jpg" },
    { name: "Atlantic Salmon", sciName: "Salmo salar", waterType: "freshwater", category: "Anadromous Salmonid", image: "images/dpi_illustrations/atlantic_salmon.jpg" },
    { name: "Murray Cod", sciName: "Maccullochella peelii", waterType: "freshwater", category: "Freshwater Apex Predator", image: "images/dpi_illustrations/murray_cod.jpg" },
    { name: "Trout Cod", sciName: "Maccullochella macquariensis", waterType: "freshwater", category: "Protected Native", image: "images/dpi_illustrations/trout_cod.jpg" },
    { name: "Eastern Freshwater Cod", sciName: "Maccullochella ikei", waterType: "freshwater", category: "Protected Native", image: "images/dpi_illustrations/eastern_freshwater_cod.jpg" },
    { name: "Mary River Cod", sciName: "Maccullochella mariensis", waterType: "freshwater", category: "Protected Native", image: "images/dpi_illustrations/mary_river_cod.jpg" },
    { name: "Macquarie Perch", sciName: "Macquaria australasica", waterType: "freshwater", category: "Protected Native Perch", image: "images/dpi_illustrations/macquarie_perch.jpg" },
    { name: "Australian Bass", sciName: "Macquaria novemaculeata", waterType: "freshwater", category: "Freshwater River Sportfish", image: "images/dpi_illustrations/australian_bass.jpg" },
    { name: "Estuary Perch", sciName: "Macquaria colonorum", waterType: "freshwater", category: "Estuary Sportfish", image: "images/dpi_illustrations/estuary_perch.jpg" },
    { name: "Silver Perch", sciName: "Bidyanus bidyanus", waterType: "freshwater", category: "Freshwater Native", image: "images/dpi_illustrations/silver_perch.jpg" },
    { name: "Golden Perch (Yellowbelly)", sciName: "Macquaria ambigua", waterType: "freshwater", category: "Freshwater Native", image: "images/dpi_illustrations/golden_perch.jpg" },
    { name: "Golden Perch", sciName: "Macquaria ambigua", waterType: "freshwater", category: "Freshwater Native", image: "images/dpi_illustrations/golden_perch.jpg" },
    { name: "Barramundi", sciName: "Lates calcarifer", waterType: "freshwater", category: "Estuary & Tropical Freshwater", image: "images/dpi_illustrations/barramundi.jpg" },
    { name: "Sooty Grunter", sciName: "Hephaestus fuliginosus", waterType: "freshwater", category: "Northern Freshwater Sportfish", image: "images/dpi_illustrations/sooty_grunter.jpg" },
    { name: "Saratoga", sciName: "Scleropages leichardti", waterType: "freshwater", category: "Ancient Freshwater Native", image: "images/dpi_illustrations/saratoga.jpg" },
    { name: "Redfin Perch", sciName: "Perca fluviatilis", waterType: "freshwater", category: "Declared Pest Species", image: "images/dpi_illustrations/redfin_perch.jpg" },
    { name: "European Carp", sciName: "Cyprinus carpio", waterType: "freshwater", category: "Noxious Pest Species", image: "images/dpi_illustrations/european_carp.jpg" },
    { name: "Tilapia", sciName: "Oreochromis mossambicus", waterType: "freshwater", category: "Declared Pest Species", image: "images/dpi_illustrations/australian_bass.jpg" },

    // Saltwater & Estuary Species
    { name: "Dusky Flathead", sciName: "Platycephalus fuscus", waterType: "saltwater", category: "Estuary Bottom Predator", image: "images/dpi_illustrations/dusky_flathead.jpg" },
    { name: "Sand Flathead", sciName: "Platycephalus bassensis", waterType: "saltwater", category: "Estuary / Coastal", image: "images/dpi_illustrations/sand_flathead.jpg" },
    { name: "Flathead (Blue-spotted/Southern)", sciName: "Platycephalus caeruleopunctatus", waterType: "saltwater", category: "Estuary / Coastal", image: "images/dpi_illustrations/flathead_bluespotted.jpg" },
    { name: "Yellowfin Bream", sciName: "Acanthopagrus australis", waterType: "saltwater", category: "Estuary / Coastal", image: "images/dpi_illustrations/yellowfin_bream.jpg" },
    { name: "Black Bream", sciName: "Acanthopagrus butcheri", waterType: "saltwater", category: "Estuary / River", image: "images/dpi_illustrations/black_bream.jpg" },
    { name: "Bream (Black)", sciName: "Acanthopagrus butcheri", waterType: "saltwater", category: "Estuary / River", image: "images/dpi_illustrations/black_bream.jpg" },
    { name: "Tarwhine", sciName: "Rhabdosargus sarba", waterType: "saltwater", category: "Estuary / Coastal", image: "images/dpi_illustrations/tarwhine.jpg" },
    { name: "Snapper", sciName: "Chrysophrys auratus", waterType: "saltwater", category: "Inshore Reef / Bay", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Pink Snapper", sciName: "Chrysophrys auratus", waterType: "saltwater", category: "Inshore Reef / Bay", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Golden Snapper", sciName: "Lutjanus johnii", waterType: "saltwater", category: "Tropical Estuary / Reef", image: "images/dpi_illustrations/golden_snapper.jpg" },
    { name: "Sand Whiting", sciName: "Sillago ciliata", waterType: "saltwater", category: "Beach / Estuary", image: "images/dpi_illustrations/sand_whiting.jpg" },
    { name: "King George Whiting", sciName: "Sillaginodes punctatus", waterType: "saltwater", category: "Inshore / Bay", image: "images/dpi_illustrations/king_george_whiting.jpg" },
    { name: "Yellowfin Whiting", sciName: "Sillago schomburgkii", waterType: "saltwater", category: "Inshore / Bay", image: "images/dpi_illustrations/yellowfin_whiting.jpg" },
    { name: "Mulloway", sciName: "Argyrosomus japonicus", waterType: "saltwater", category: "Estuary & Coastal Apex", image: "images/dpi_illustrations/mulloway.jpg" },
    { name: "Yellowtail Kingfish", sciName: "Seriola lalandi", waterType: "saltwater", category: "Inshore / Offshore Reef", image: "images/dpi_illustrations/yellowtail_kingfish.jpg" },
    { name: "Kingfish (Yellowtail)", sciName: "Seriola lalandi", waterType: "saltwater", category: "Inshore / Offshore Reef", image: "images/dpi_illustrations/yellowtail_kingfish.jpg" },
    { name: "Australian Salmon", sciName: "Arripis truttaceus", waterType: "saltwater", category: "Coastal Pelagic", image: "images/dpi_illustrations/australian_salmon.jpg" },
    { name: "Salmon (Western Australian)", sciName: "Arripis truttaceus", waterType: "saltwater", category: "Coastal Pelagic", image: "images/dpi_illustrations/australian_salmon.jpg" },
    { name: "Tailor", sciName: "Pomatomus saltatrix", waterType: "saltwater", category: "Estuary & Surf Pelagic", image: "images/dpi_illustrations/tailor.jpg" },
    { name: "Luderick (Blackfish)", sciName: "Girella tricuspidata", waterType: "saltwater", category: "Estuary & Rock Fishing", image: "images/dpi_illustrations/luderick.jpg" },
    { name: "Luderick", sciName: "Girella tricuspidata", waterType: "saltwater", category: "Estuary & Rock Fishing", image: "images/dpi_illustrations/luderick.jpg" },
    { name: "Garfish", sciName: "Hyporhamphus melanochir", waterType: "saltwater", category: "Inshore / Bay", image: "images/dpi_illustrations/garfish.jpg" },
    { name: "Sea Garfish", sciName: "Hyporhamphus melanochir", waterType: "saltwater", category: "Inshore / Bay", image: "images/dpi_illustrations/garfish.jpg" },
    { name: "Striped Trumpeter", sciName: "Latris lineata", waterType: "saltwater", category: "Deep Reef", image: "images/dpi_illustrations/striped_trumpeter.jpg" },
    { name: "Queenfish", sciName: "Scomberoides commersonnianus", waterType: "saltwater", category: "Tropical Pelagic", image: "images/dpi_illustrations/queenfish.jpg" },
    { name: "Eastern Blue Groper", sciName: "Achoerodus viridis", waterType: "saltwater", category: "Protected Coastal Wrasse", image: "images/dpi_illustrations/eastern_blue_groper.jpg" },
    { name: "Giant Trevally (GT)", sciName: "Caranx ignobilis", waterType: "saltwater", category: "Pelagic / Flats Predator", image: "images/dpi_illustrations/giant_trevally.jpg" },
    { name: "Giant Trevally", sciName: "Caranx ignobilis", waterType: "saltwater", category: "Pelagic / Flats Predator", image: "images/dpi_illustrations/giant_trevally.jpg" },
    { name: "Silver Trevally", sciName: "Pseudocaranx georgianus", waterType: "saltwater", category: "Inshore / Bay", image: "images/dpi_illustrations/silver_trevally.jpg" },
    { name: "Golden Trevally", sciName: "Gnathanodon speciosus", waterType: "saltwater", category: "Flats Predator", image: "images/dpi_illustrations/giant_trevally.jpg" },
    { name: "Mangrove Jack", sciName: "Lutjanus argentimaculatus", waterType: "saltwater", category: "Estuary / Structure", image: "images/dpi_illustrations/mangrove_jack.jpg" },
    { name: "Coral Trout", sciName: "Plectropomus leopardus", waterType: "saltwater", category: "Reef Predator", image: "images/dpi_illustrations/snapper.jpg" },
    { name: "Spanish Mackerel", sciName: "Scomberomorus commerson", waterType: "saltwater", category: "Pelagic Speedster", image: "images/dpi_illustrations/spanish_mackerel.jpg" },
    { name: "Bonefish", sciName: "Albula vulpes", waterType: "saltwater", category: "Tropical Flats Speedster", image: "images/dpi_illustrations/sand_whiting.jpg" },
    { name: "Tarpon", sciName: "Megalops atlanticus", waterType: "saltwater", category: "Tropical Megalops / Estuary", image: "images/dpi_illustrations/barramundi.jpg" },
    { name: "Permit", sciName: "Trachinotus falcatus", waterType: "saltwater", category: "Tropical Flats Gamefish", image: "images/dpi_illustrations/silver_trevally.jpg" },
    { name: "Mahi Mahi (Dorado)", sciName: "Coryphaena hippurus", waterType: "saltwater", category: "Offshore Bluewater", image: "images/dpi_illustrations/mahi_mahi.jpg" }
];
