// regulations.js - Australian Fish Size and Bag Regulations (Aligned with Official DPI/VFA/PIRSA/DPIRD Guidelines)

const REGULATIONS = {
    NSW: {
        stateName: "New South Wales",
        freshwater: [
            { name: "Murray Cod", minSize: 55, maxSize: 75, bagLimit: "2 (only 1 in rivers)", possessionLimit: "4", season: "Closed Sept 1 - Nov 30 (except Copeton & Blowering Dams)" },
            { name: "Golden Perch (Yellowbelly)", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Rainbow Trout", minSize: 25, maxSize: null, bagLimit: "5 (dams/lakes), 2 (streams)", possessionLimit: "10", season: "Streams closed June long weekend - Oct long weekend" },
            { name: "Brown Trout", minSize: 25, maxSize: null, bagLimit: "5 (dams/lakes), 2 (streams)", possessionLimit: "10", season: "Streams closed June long weekend - Oct long weekend" },
            { name: "Brook Trout", minSize: 25, maxSize: null, bagLimit: "5 (dams/lakes), 2 (streams)", possessionLimit: "10", season: "Streams closed June long weekend - Oct long weekend" },
            { name: "Atlantic Salmon", minSize: 25, maxSize: null, bagLimit: "5 (dams/lakes), 2 (streams)", possessionLimit: "10", season: "Streams closed June long weekend - Oct long weekend" },
            { name: "Australian Bass", minSize: 0, maxSize: null, bagLimit: "2 (combined with Estuary Perch; only 1 > 35cm in rivers)", possessionLimit: "4", season: "Rivers closed May 1 - Aug 31 (Catch & release permitted)" },
            { name: "Estuary Perch", minSize: 0, maxSize: null, bagLimit: "2 (combined with Bass; only 1 > 35cm in rivers)", possessionLimit: "4", season: "Rivers closed May 1 - Aug 31 (Catch & release permitted)" },
            { name: "Silver Perch", minSize: 25, maxSize: null, bagLimit: "5 (Listed dams only)", possessionLimit: "10", season: "Protected in all rivers (0 bag limit in all rivers)" },
            { name: "Freshwater Catfish (Eel-tailed Catfish)", minSize: 30, maxSize: null, bagLimit: "2 (Listed dams/eastern drainages only)", possessionLimit: "4", season: "Protected / 0 bag limit in western Murray-Darling rivers" },
            { name: "River Blackfish", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Check local river closures & regulations" },
            { name: "Two-spined Blackfish", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "High country alpine streams" },
            { name: "Spangled Perch", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Bony Bream (Pyramid Bream)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Long-finned Eel", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Short-finned Eel", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Macquarie Perch", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered native fish. Total no-take closure in all NSW waters" },
            { name: "Trout Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered native fish. Total closure, return to water immediately" },
            { name: "Eastern Freshwater Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered native fish. Total closure in northern coastal rivers" },
            { name: "Southern Purple-Spotted Gudgeon", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered native fish. Total closure" },
            { name: "Olive Perchlet", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered native fish. Total closure" },
            { name: "Southern Pygmy Perch", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Threatened native fish. Total closure" },
            { name: "Murray Hardyhead", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered native fish. Total closure" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared noxious pest. Illegal to return to water alive" },
            { name: "Redfin Perch", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared pest. Do not return to water alive" },
            { name: "Eastern Mosquitofish (Gambusia)", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared noxious pest" },
            { name: "Goldfish", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared non-native pest" },
            { name: "Oriental Weatherloach", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared noxious pest" }
        ],
        saltwater: [
            { name: "Dusky Flathead", minSize: 36, maxSize: 70, bagLimit: "5", possessionLimit: "10", season: "Open all year (Slot limit 36–70cm, all > 70cm must be released)" },
            { name: "Sand Flathead", minSize: 33, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year (Combined with Tiger Flathead)" },
            { name: "Tiger Flathead", minSize: 33, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Bluespotted Flathead", minSize: 33, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Yellowfin Bream", minSize: 25, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year (Combined with Black Bream & Tarwhine)" },
            { name: "Black Bream", minSize: 25, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Tarwhine", minSize: 20, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Snapper", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year (Only 1 > 70cm recommended)" },
            { name: "Sand Whiting", minSize: 27, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Trumpeter Whiting (Winter Whiting)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "King George Whiting", minSize: 32, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Mulloway", minSize: 70, maxSize: null, bagLimit: "1", possessionLimit: "2", season: "Open all year (Boat limit of 2 applied)" },
            { name: "Teraglin", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Yellowtail Kingfish", minSize: 65, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Samsonfish", minSize: 65, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Combined with Kingfish & Amberjack)" },
            { name: "Amberjack", minSize: 65, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Australian Salmon", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year (No min size limit)" },
            { name: "Tailor", minSize: 30, maxSize: null, bagLimit: "10 (only 5 over 35cm)", possessionLimit: "20", season: "Open all year" },
            { name: "Luderick (Blackfish)", minSize: 27, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Rock Blackfish (Black Drummer)", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Silver Drummer", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Silver Trevally", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Giant Trevally (GT)", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Bigeye Trevally", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Golden Trevally", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Mangrove Jack", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Mahi Mahi (Dorado)", minSize: 60, maxSize: null, bagLimit: "10 (only 1 over 110cm)", possessionLimit: "20", season: "Open all year" },
            { name: "Spanish Mackerel", minSize: 75, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Spotted Mackerel", minSize: 60, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "School Mackerel", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Wahoo", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Cobia (Black Kingfish)", minSize: 65, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Yellowfin Tuna", minSize: 90, maxSize: null, bagLimit: "5 (max 2 over 90cm across all large tuna combined)", possessionLimit: "5", season: "Open all year" },
            { name: "Southern Bluefin Tuna", minSize: 90, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year (Max 1 fish total)" },
            { name: "Bigeye Tuna", minSize: 90, maxSize: null, bagLimit: "5 (max 2 over 90cm combined)", possessionLimit: "5", season: "Open all year" },
            { name: "Albacore Tuna", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Longtail Tuna (Northern Bluefin)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Skipjack Tuna (Striped Tuna)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Mackerel Tuna (Little Tunny)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Australian Bonito", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Striped Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Blue Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Black Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Sailfish", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Broadbill Swordfish", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Shortbill Spearfish", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Eastern Blue Groper", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Official NSW State Fish. Complete prohibition on line fishing & spearfishing" },
            { name: "Blue Morwong (Rubberlip Morwong)", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Jackass Morwong (Grey Morwong / Jackass Fish)", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Red Morwong", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Pearl Perch", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Moses Snapper (Moses Perch)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Golden Snapper (Fingermark)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Bar Cod (Band-ed Rockcod)", minSize: 0, maxSize: null, bagLimit: "5 (combined deep sea)", possessionLimit: "5", season: "Open all year" },
            { name: "Bass Groper", minSize: 0, maxSize: null, bagLimit: "5 (combined deep sea)", possessionLimit: "5", season: "Open all year" },
            { name: "Hapuku", minSize: 0, maxSize: null, bagLimit: "5 (combined deep sea)", possessionLimit: "5", season: "Open all year" },
            { name: "Blue-eye Trevalla", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Gemfish", minSize: 0, maxSize: null, bagLimit: "5 (boat limit 10)", possessionLimit: "5", season: "Open all year" },
            { name: "Sea Garfish (Eastern Sea Garfish)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "River Garfish", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Yellowtail Scad (Yakker)", minSize: 0, maxSize: null, bagLimit: "50", possessionLimit: "50", season: "Open all year" },
            { name: "Slimy Mackerel (Pacific Mackerel)", minSize: 0, maxSize: null, bagLimit: "50", possessionLimit: "50", season: "Open all year" },
            { name: "Yellowfin Leatherjacket", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Six-spined Leatherjacket", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Flounder (Greenback & Small-toothed)", minSize: 25, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Sole (Black Sole / Many-banded Sole)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "John Dory", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Mirror Dory", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Silver Sweep", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Red Gurnard", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Sea Mullet (Bully Mullet)", minSize: 30, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Flat-tail Mullet / Sand Mullet", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Sergeant Baker", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Coral Trout (Bar-cheek & Leopard)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Gummy Shark", minSize: 0, maxSize: null, bagLimit: "5 (combined shark limit)", possessionLimit: "5", season: "Open all year" },
            { name: "School Shark", minSize: 91, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Mako Shark", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Tiger Shark", minSize: 0, maxSize: null, bagLimit: "1 (only 1 > 1.5m)", possessionLimit: "1", season: "Open all year" },
            { name: "Hammerhead Shark (Smooth)", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Great White Shark (White Pointer)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically protected. Total prohibition on taking or harming" },
            { name: "Grey Nurse Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered. Total prohibition" },
            { name: "Scalloped Hammerhead Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered. Total prohibition" },
            { name: "Great Hammerhead Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered. Total prohibition" },
            { name: "Black Rockcod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected marine fish. Total prohibition in all NSW waters" },
            { name: "Ballina Angelfish", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected marine fish. Total prohibition" }
        ]
    },
    VIC: {
        stateName: "Victoria",
        freshwater: [
            { name: "Murray Cod", minSize: 55, maxSize: 75, bagLimit: "1 (Rivers), 2 (Lakes)", possessionLimit: "4", season: "Closed Sept 1 - Nov 30 (except Lake Eildon & Wimmera Basin)" },
            { name: "Golden Perch", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Brown Trout", minSize: 0, maxSize: null, bagLimit: "5 (only 2 over 35cm in streams)", possessionLimit: "10", season: "Streams closed June long weekend to Sept first Saturday (Lakes open all year)" },
            { name: "Rainbow Trout", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Streams closed June long weekend to Sept first Saturday (Lakes open all year)" },
            { name: "Brook Trout", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Streams closed June long weekend to Sept first Saturday (Lakes open all year)" },
            { name: "Tiger Trout", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Stocked crater lakes (Open all year in lakes)" },
            { name: "Cheetah Trout", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Stocked crater lakes (Open all year in lakes)" },
            { name: "Atlantic Salmon", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Stocked lakes / impoundments" },
            { name: "Chinook Salmon (Quinnat Salmon)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Stocked crater lakes (Lake Purrumbete & Bullen Merri)" },
            { name: "Australian Bass", minSize: 27, maxSize: null, bagLimit: "2 (Bag 5 in Lake Bullen Merri)", possessionLimit: "4", season: "Open all year (Combined Bass/Estuary Perch limit 5 in total)" },
            { name: "Estuary Perch", minSize: 27, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year (Combined with Australian Bass)" },
            { name: "Silver Perch", minSize: 30, maxSize: null, bagLimit: "5 (Stocked dams only)", possessionLimit: "10", season: "Rivers closed all year (Protected in all native river drainages north of Great Dividing Range)" },
            { name: "Freshwater Catfish (Eel-tailed Catfish)", minSize: 30, maxSize: null, bagLimit: "2 (Wimmera Basin only)", possessionLimit: "4", season: "Rivers and streams total closure across rest of Victoria (Protected)" },
            { name: "River Blackfish", minSize: 30, maxSize: null, bagLimit: "2 (combined)", possessionLimit: "4", season: "South of Great Dividing Range min 30cm, closed Sept 1 - Dec 31; North min 0cm" },
            { name: "Two-spined Blackfish", minSize: 30, maxSize: null, bagLimit: "2 (combined)", possessionLimit: "4", season: "Closed Sept 1 - Dec 31 south of Great Dividing Range" },
            { name: "Trout Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected endangered native. Total closure" },
            { name: "Macquarie Perch", minSize: "Protected (most areas)", maxSize: "N/A", bagLimit: "0 (Rivers) / 1 (Lake Dartmouth, min 35cm)", possessionLimit: "2", season: "Protected in all rivers. Strict seasonal closure May 1 - Dec 31 at Lake Dartmouth" },
            { name: "Long-finned Eel", minSize: 30, maxSize: null, bagLimit: "10 (combined)", possessionLimit: "20", season: "Open all year" },
            { name: "Short-finned Eel", minSize: 30, maxSize: null, bagLimit: "10 (combined)", possessionLimit: "20", season: "Open all year" },
            { name: "Common Galaxias (Jollytail)", minSize: 0, maxSize: null, bagLimit: "40 (combined small native fish)", possessionLimit: "40", season: "Open all year (Protected for threatened Galaxias species)" },
            { name: "Southern Purple-Spotted Gudgeon", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected native fish. Total prohibition" },
            { name: "Tench", minSize: "No Limit", maxSize: "N/A", bagLimit: "5", possessionLimit: "10", season: "Naturalised freshwater species" },
            { name: "Roach", minSize: "No Limit", maxSize: "N/A", bagLimit: "5", possessionLimit: "10", season: "Naturalised freshwater species" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Noxious pest species. Illegal to return to water alive" },
            { name: "Redfin Perch", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Open all year" },
            { name: "Oriental Weatherloach", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Noxious declared pest. Do not return to water alive" },
            { name: "Eastern Mosquitofish (Gambusia)", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Noxious declared pest" },
            { name: "Goldfish", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared pest species" }
        ],
        saltwater: [
            { name: "Black Bream", minSize: 28, maxSize: null, bagLimit: "10 (Bag 7, Slot 28-38cm in Gippsland Lakes)", possessionLimit: "20", season: "Open all year (Combined bream/tarwhine total 10)" },
            { name: "Yellowfin Bream", minSize: 28, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Tarwhine", minSize: 28, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Dusky Flathead", minSize: 30, maxSize: 55, bagLimit: "5", possessionLimit: "10", season: "Open all year (Slot 30-55cm; all > 55cm must be released. Lake Tyers and east: all flathead treated as Dusky)" },
            { name: "Sand Flathead", minSize: 27, maxSize: null, bagLimit: "20 (combined)", possessionLimit: "40", season: "Open all year" },
            { name: "Tiger Flathead", minSize: 27, maxSize: null, bagLimit: "20 (combined)", possessionLimit: "40", season: "Open all year" },
            { name: "Bluespotted Flathead", minSize: 27, maxSize: null, bagLimit: "20 (combined)", possessionLimit: "40", season: "Open all year" },
            { name: "King George Whiting", minSize: 27, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Sand Whiting", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Trumpeter Whiting (Winter Whiting)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Snapper", minSize: 28, maxSize: null, bagLimit: "10 (only 3 over 40cm)", possessionLimit: "20", season: "Open all year" },
            { name: "Mulloway", minSize: 60, maxSize: null, bagLimit: "5 (only 2 over 100cm)", possessionLimit: "10", season: "Open all year" },
            { name: "Estuary Perch", minSize: 27, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year (Combined with Australian Bass)" },
            { name: "Australian Salmon", minSize: 0, maxSize: null, bagLimit: "20 (only 5 over 35cm in Port Phillip/Western Port)", possessionLimit: "40", season: "Open all year (Combined with Australian Herring)" },
            { name: "Australian Herring (Tommy Ruff)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year (Combined with Australian Salmon)" },
            { name: "Silver Trevally", minSize: 20, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Yellowtail Kingfish", minSize: 60, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year" },
            { name: "Tailor", minSize: 23, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Luderick", minSize: 23, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Garfish", minSize: 0, maxSize: null, bagLimit: "40", possessionLimit: "80", season: "Open all year" },
            { name: "Flounder (Greenback & Small-toothed)", minSize: 23, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Sole (Black Sole / Many-banded Sole)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "General species limit applies" },
            { name: "Yellow-eye Mullet", minSize: 0, maxSize: null, bagLimit: "40", possessionLimit: "80", season: "Open all year" },
            { name: "Sea Mullet (Bully Mullet)", minSize: 0, maxSize: null, bagLimit: "40", possessionLimit: "80", season: "Open all year" },
            { name: "Flat-tail Mullet / Sand Mullet", minSize: 0, maxSize: null, bagLimit: "40", possessionLimit: "80", season: "Open all year" },
            { name: "Snook (Australian Pike)", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Barracouta (Snoek)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Blue Warehou", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Leatherjacket (Six-spined & Yellowfin)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Blue-throated Wrasse", minSize: 27, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year (Combined wrasse limit 5)" },
            { name: "Elephant Fish", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "2", season: "Open all year" },
            { name: "John Dory", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Mirror Dory", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Red Gurnard", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Silver Sweep", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Striped Trumpeter", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Blue-eye Trevalla", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Gemfish", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Blue Morwong (Rubberlip Morwong)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Jackass Morwong (Grey Morwong / Jackass Fish)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Red Morwong", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Yellowtail Scad (Yakker)", minSize: 0, maxSize: null, bagLimit: "40", possessionLimit: "80", season: "Open all year" },
            { name: "Slimy Mackerel (Pacific Mackerel)", minSize: 0, maxSize: null, bagLimit: "40", possessionLimit: "80", season: "Open all year" },
            { name: "Australian Pilchard (Sardine)", minSize: 0, maxSize: null, bagLimit: "40", possessionLimit: "80", season: "Open all year (Combined with Anchovy)" },
            { name: "Australian Anchovy", minSize: 0, maxSize: null, bagLimit: "40", possessionLimit: "80", season: "Open all year (Combined with Pilchard)" },
            { name: "Southern Bluefin Tuna", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Combined tuna limit 2 (State-wide strict possession limit 2)" },
            { name: "Yellowfin Tuna", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Combined tuna limit 2" },
            { name: "Bigeye Tuna", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Combined tuna limit 2" },
            { name: "Albacore Tuna", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Combined tuna limit 5" },
            { name: "Skipjack Tuna", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Combined tuna limit 5" },
            { name: "Australian Bonito", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Gummy Shark", minSize: 45, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Carcass length 45cm / total length 75cm (Combined gummy & school shark limit 2)" },
            { name: "School Shark", minSize: 45, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Carcass length 45cm / total length 75cm (Combined gummy & school shark limit 2)" },
            { name: "Mako Shark", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Great White Shark (White Pointer)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected apex predator. Total prohibition in all Victorian waters" },
            { name: "Grey Nurse Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered shark. Total prohibition" }
        ]
    },
    QLD: {
        stateName: "Queensland",
        freshwater: [
            { name: "Barramundi", minSize: 58, maxSize: 120, bagLimit: "5", possessionLimit: "5", season: "Closed Nov 1 - Feb 1 (East Coast rivers); Oct 7 - Jan 31 (Gulf of Carpentaria)" },
            { name: "Golden Perch", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Murray Cod", minSize: 60, maxSize: 110, bagLimit: "2", possessionLimit: "2", season: "Closed Aug 1 - Oct 31 in QLD waters" },
            { name: "Sooty Grunter", minSize: 28, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Saratoga", minSize: 50, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Silver Perch", minSize: 30, maxSize: null, bagLimit: "5 (Stocked dams only)", possessionLimit: "5", season: "Protected / 0 bag in natural river drainages" },
            { name: "Freshwater Catfish (Eel-tailed Catfish)", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Mary River Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected endangered native. Total closure in Mary River system" },
            { name: "Speartooth Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered river shark. Total no-take closure" },
            { name: "Sawfish (Freshwater & Green)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered. Total no-take closure" },
            { name: "Tilapia", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared noxious pest. Euthanise humanely, do not release" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared pest. Illegal to return to water alive" }
        ],
        saltwater: [
            { name: "Barramundi", minSize: 58, maxSize: 120, bagLimit: "5", possessionLimit: "5", season: "East Coast closed Nov 1 - Feb 1; Gulf closed Oct 7 - Jan 31 (Slot limit 58-120cm)" },
            { name: "Black Jewfish", minSize: 75, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year (Closed periods apply by management zone once quota reached)" },
            { name: "Mulloway", minSize: 75, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Teraglin", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Snapper", minSize: 35, maxSize: null, bagLimit: "4 (only 1 over 70cm)", possessionLimit: "4", season: "Closed July 15 - Aug 15" },
            { name: "Pearl Perch", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Closed July 15 - Aug 15" },
            { name: "Dusky Flathead", minSize: 40, maxSize: 75, bagLimit: "5", possessionLimit: "5", season: "Open all year (Slot limit 40-75cm, all > 75cm must be released)" },
            { name: "Sand Flathead", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Yellowfin Bream", minSize: 25, maxSize: null, bagLimit: "30", possessionLimit: "30", season: "Open all year (Combined bream/tarwhine total 30)" },
            { name: "Black Bream", minSize: 25, maxSize: null, bagLimit: "30", possessionLimit: "30", season: "Open all year" },
            { name: "Pikey Bream", minSize: 25, maxSize: null, bagLimit: "30", possessionLimit: "30", season: "Open all year" },
            { name: "Tarwhine", minSize: 25, maxSize: null, bagLimit: "30", possessionLimit: "30", season: "Open all year" },
            { name: "Sand Whiting", minSize: 25, maxSize: null, bagLimit: "30", possessionLimit: "30", season: "Open all year (Combined whiting limit 30)" },
            { name: "Goldenline Whiting", minSize: 25, maxSize: null, bagLimit: "30", possessionLimit: "30", season: "Open all year" },
            { name: "Trumpeter Whiting (Winter Whiting)", minSize: 0, maxSize: null, bagLimit: "50", possessionLimit: "50", season: "Open all year" },
            { name: "Tailor", minSize: 35, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year (Fraser Island/K'gari closed Aug 1 - Sept 30)" },
            { name: "Mangrove Jack", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Red Emperor", minSize: 55, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Combined coral reef fin fish max 20)" },
            { name: "Crimson Snapper (Crimson Seaperch / Small-mouth Nannygai)", minSize: 40, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Combined coral reef fin fish)" },
            { name: "Saddletail Snapper (Saddletail Seaperch / Large-mouth Nannygai)", minSize: 40, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Combined coral reef fin fish)" },
            { name: "Golden Snapper (Fingermark)", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Russell's Snapper (Moses Snapper / Moses Perch)", minSize: 25, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Stripey Snapper (Spanish Flag)", minSize: 25, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Hussar", minSize: 25, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Coral Trout", minSize: 38, maxSize: null, bagLimit: "7", possessionLimit: "7", season: "Combined coral reef fin fish max 20; Coral reef fin fish closures apply in Oct/Nov" },
            { name: "Barramundi Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected coral reef species. Total no-take closure" },
            { name: "Queensland Groper (Giant Grouper)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected marine species. Total no-take closure" },
            { name: "Potato Rockcod (Potato Cod)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected reef cod. Total no-take closure" },
            { name: "Humphead Maori Wrasse", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected coral reef wrasse. Total no-take closure" },
            { name: "Estuary Cod (Goldspotted & Blackspotted Rockcod)", minSize: 38, maxSize: 100, bagLimit: "5", possessionLimit: "5", season: "Open all year (Slot limit 38-100cm; combined cod/grouper limit)" },
            { name: "Coral Rockcod", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Maori Rockcod", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Flowery Cod", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Spanish Mackerel", minSize: 75, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Northern closure (Oct-Nov) & Southern closure (Feb-Mar) apply" },
            { name: "Spotted Mackerel", minSize: 60, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "School Mackerel", minSize: 50, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Grey Mackerel (Broadbarred)", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Shark Mackerel", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Wahoo", minSize: 75, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Cobia (Black Kingfish)", minSize: 75, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Yellowtail Kingfish", minSize: 60, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Samsonfish", minSize: 50, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Amberjack", minSize: 50, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Giant Trevally (GT)", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Combined trevally possession limit 5)" },
            { name: "Bigeye Trevally", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Golden Trevally", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Queenfish", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Mahi Mahi (Dorado)", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Yellowfin Tuna", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year (Combined tuna possession limit 5)" },
            { name: "Longtail Tuna (Northern Bluefin)", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Mackerel Tuna (Little Tunny)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Skipjack Tuna", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Albacore Tuna", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Bigeye Tuna", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Striped Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Blue Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Black Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Sailfish", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Broadbill Swordfish", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Spangled Emperor", minSize: 45, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Combined emperor limit)" },
            { name: "Redthroat Emperor (Sweetlip)", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Grass Emperor (Sweetlip)", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Lancer (Redspot Emperor)", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Longnose Emperor", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Luderick (Blackfish)", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Silver Trevally", minSize: 25, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Garfish", minSize: 0, maxSize: null, bagLimit: "50", possessionLimit: "50", season: "Open all year" },
            { name: "Yellowtail Scad (Yakker)", minSize: 0, maxSize: null, bagLimit: "50", possessionLimit: "50", season: "Open all year" },
            { name: "Slimy Mackerel (Pacific Mackerel)", minSize: 0, maxSize: null, bagLimit: "50", possessionLimit: "50", season: "Open all year" },
            { name: "Flounder (Greenback & Small-toothed)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "General tidal possession limit applies" },
            { name: "Sole (Black Sole / Many-banded Sole)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "General tidal possession limit applies" },
            { name: "Sea Mullet (Bully Mullet)", minSize: 30, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year (Others no size limit)" },
            { name: "Flat-tail Mullet / Sand Mullet", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Tiger Shark", minSize: 0, maxSize: 150, bagLimit: "1", possessionLimit: "1", season: "Max 1.5m length limit across all sharks; total shark limit 1" },
            { name: "Gummy Shark", minSize: 0, maxSize: 150, bagLimit: "1", possessionLimit: "1", season: "Max 1.5m length limit across all sharks; total shark limit 1" },
            { name: "Mako Shark", minSize: 0, maxSize: 150, bagLimit: "1", possessionLimit: "1", season: "Max 1.5m length limit across all sharks; total shark limit 1" },
            { name: "Great White Shark (White Pointer)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected apex predator. Total no-take closure" },
            { name: "Grey Nurse Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered shark. Total no-take closure" }
        ]
    },
    WA: {
        stateName: "Western Australia",
        freshwater: [
            { name: "Rainbow Trout", minSize: 30, maxSize: null, bagLimit: "4 (within mixed freshwater limit)", possessionLimit: "8", season: "Open during SW freshwater angling season (Closed July 1 - Aug 31 in rivers)" },
            { name: "Brown Trout", minSize: 30, maxSize: null, bagLimit: "4 (within mixed freshwater limit)", possessionLimit: "8", season: "Open during SW freshwater angling season (Closed July 1 - Aug 31 in rivers)" },
            { name: "Freshwater Cobbler", minSize: 0, maxSize: null, bagLimit: "4", possessionLimit: "8", season: "Open all year" },
            { name: "Sooty Grunter", minSize: 25, maxSize: null, bagLimit: "4", possessionLimit: "8", season: "Open all year in northern freshwater systems" },
            { name: "Australian Grayling", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected native freshwater fish" },
            { name: "Redfin Perch", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Controlled pest species. Do not return to water alive" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Noxious pest. Humane disposal required" }
        ],
        saltwater: [
            { name: "West Australian Dhufish", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 1 (Other bioregions)", possessionLimit: "10kg fillets or 2 days bag limit", season: "West Coast boat demersal closure applies until Spring 2027. Land-based fishing permitted (Spearfishing prohibited)" },
            { name: "Baldchin Groper", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 2 (Other bioregions)", possessionLimit: "General finfish possession applies", season: "Closed at Abrolhos Islands Oct 1 - Dec 31 (West Coast demersal boat closure applies)" },
            { name: "Western Blue Groper", minSize: 50, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year (West Coast demersal boat closure applies)" },
            { name: "Pink Snapper", minSize: 41, maxSize: null, bagLimit: "2 (West Coast & Other), 1 (Abrolhos)", possessionLimit: "General finfish possession applies", season: "Min 50cm Lancelin to Black Point, 41cm Lancelin to Zuytdorp Cliffs, 45cm elsewhere. Cockburn & Warnbro Sounds closed Aug 1 - Jan 31; Shark Bay closures apply" },
            { name: "Red Emperor", minSize: 45, maxSize: null, bagLimit: "2 (West Coast & Other), 1 (Abrolhos)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Coral Trout", minSize: 45, maxSize: null, bagLimit: "1", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Coronation Trout", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Blackspot Tuskfish", minSize: 40, maxSize: null, bagLimit: "2 (West Coast & Other), 1 (Abrolhos)", possessionLimit: "General finfish possession applies", season: "Open all year (Other tuskfish species No Limit size)" },
            { name: "Blue Morwong (Queen Snapper)", minSize: 40, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Goldspotted Rockcod (Estuary Cod)", minSize: 40, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Breaksea Cod (Blackass)", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Rankin Cod", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Western Wirrah", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Harlequin Fish", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Barramundi Cod", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Spangled Emperor", minSize: 40, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Redthroat Emperor", minSize: 30, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Grass Emperor", minSize: 30, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Bight Redfish", minSize: 35, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year (South Coast special allowance: 4 Bight redfish, 4 Yelloweye redfish, 4 Swallowtail + mixed bag)" },
            { name: "Yelloweye Redfish", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Swallowtail", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Western Foxfish", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Goldspot Pigfish", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Hapuku", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Bass Groper", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Blue-eye Trevalla", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Pearl Perch", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "John Dory", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "May be taken during West Coast demersal closure" },
            { name: "Mirror Dory", minSize: 0, maxSize: null, bagLimit: "2 (West Coast), 1 (Abrolhos), 4 (Other)", possessionLimit: "General finfish possession applies", season: "May be taken during West Coast demersal closure" },
            { name: "Spanish Mackerel", minSize: 90, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Grey Mackerel (Broadbarred)", minSize: 75, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "School Mackerel", minSize: 50, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Spotted Mackerel", minSize: 50, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Shark Mackerel", minSize: 50, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Cobia", minSize: 75, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Amberjack", minSize: 60, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Samsonfish", minSize: 60, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Yellowtail Kingfish", minSize: 60, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Wahoo", minSize: 90, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Mahi Mahi (Dorado)", minSize: 50, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Blue Marlin", minSize: 0, maxSize: null, bagLimit: "1 (individual species limit)", possessionLimit: "1", season: "Open all year (Billfish group limit 1)" },
            { name: "Black Marlin", minSize: 0, maxSize: null, bagLimit: "1 (individual species limit)", possessionLimit: "1", season: "Open all year (Billfish group limit 1)" },
            { name: "Striped Marlin", minSize: 0, maxSize: null, bagLimit: "1 (individual species limit)", possessionLimit: "1", season: "Open all year (Billfish group limit 1)" },
            { name: "Sailfish", minSize: 0, maxSize: null, bagLimit: "1 (individual species limit)", possessionLimit: "1", season: "Open all year (Billfish group limit 1)" },
            { name: "Broadbill Swordfish", minSize: 0, maxSize: null, bagLimit: "1 (individual species limit)", possessionLimit: "1", season: "Open all year" },
            { name: "Giant Trevally", minSize: 0, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Golden Trevally", minSize: 0, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Bigeye Tuna", minSize: 0, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Dogtooth Tuna", minSize: 0, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Longtail Tuna (Northern Bluefin)", minSize: 0, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Mackerel Tuna (Little Tunny)", minSize: 0, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Skipjack Tuna", minSize: 0, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Southern Bluefin Tuna", minSize: 0, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Yellowfin Tuna", minSize: 0, maxSize: null, bagLimit: "3 (within large pelagic mixed limit)", possessionLimit: "General finfish possession applies", season: "Open all year" },
            { name: "Barramundi", minSize: 55, maxSize: 80, bagLimit: "2", possessionLimit: "2 whole or 4 fillets", season: "Must be landed as whole fish (Slot 55-80cm)" },
            { name: "Black Bream", minSize: 25, maxSize: null, bagLimit: "6", possessionLimit: "12", season: "Open all year (Swan & Canning rivers: only 2 black bream over 40cm)" },
            { name: "Tarwhine", minSize: 25, maxSize: null, bagLimit: "6", possessionLimit: "12", season: "Open all year" },
            { name: "Northwest Black Bream", minSize: 25, maxSize: null, bagLimit: "6", possessionLimit: "12", season: "Open all year" },
            { name: "Western Yellowfin Bream", minSize: 30, maxSize: null, bagLimit: "6", possessionLimit: "12", season: "Open all year" },
            { name: "Tailor", minSize: 30, maxSize: null, bagLimit: "8 (only 2 over 50cm)", possessionLimit: "16", season: "Open all year" },
            { name: "Western Australian Salmon", minSize: 30, maxSize: null, bagLimit: "4", possessionLimit: "8", season: "Open all year" },
            { name: "King George Whiting", minSize: 28, maxSize: null, bagLimit: "12", possessionLimit: "24", season: "Open all year" },
            { name: "Yellowfin Whiting", minSize: 0, maxSize: null, bagLimit: "30", possessionLimit: "60", season: "Open all year" },
            { name: "Flathead", minSize: 30, maxSize: null, bagLimit: "8", possessionLimit: "16", season: "Open all year" },
            { name: "Flounder", minSize: 25, maxSize: null, bagLimit: "8", possessionLimit: "16", season: "Open all year" },
            { name: "Mangrove Jack", minSize: 30, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year" },
            { name: "Black Jewfish", minSize: 70, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year" },
            { name: "Mulloway", minSize: 50, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year" },
            { name: "Golden Snapper (Fingermark)", minSize: 30, maxSize: null, bagLimit: "4", possessionLimit: "8", season: "Open all year" },
            { name: "King Threadfin", minSize: 45, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year" },
            { name: "Blue Threadfin", minSize: 0, maxSize: null, bagLimit: "4", possessionLimit: "8", season: "Open all year" },
            { name: "Tripletail", minSize: 30, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year" },
            { name: "Stripey Snapper", minSize: 30, maxSize: null, bagLimit: "4", possessionLimit: "8", season: "Open all year" },
            { name: "Silver Trevally", minSize: 25, maxSize: null, bagLimit: "8", possessionLimit: "16", season: "Open all year (Skippy)" },
            { name: "Queenfish", minSize: 0, maxSize: null, bagLimit: "8", possessionLimit: "16", season: "Open all year" },
            { name: "Chinaman Rockcod (Charlie Court)", minSize: 0, maxSize: null, bagLimit: "4", possessionLimit: "8", season: "Open all year" },
            { name: "Western King Wrasse", minSize: 0, maxSize: null, bagLimit: "8", possessionLimit: "16", season: "Open all year" },
            { name: "Australian Herring (Tommy Ruff)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Sea Garfish", minSize: 0, maxSize: null, bagLimit: "30", possessionLimit: "60", season: "Open all year" },
            { name: "Yellow-eye Mullet", minSize: 0, maxSize: null, bagLimit: "30", possessionLimit: "60", season: "Open all year" },
            { name: "Slimy Mackerel (Pacific Mackerel)", minSize: 0, maxSize: null, bagLimit: "30", possessionLimit: "60", season: "Open all year" },
            { name: "Gummy Shark", minSize: 0, maxSize: null, bagLimit: "3 (combined sharks and rays limit)", possessionLimit: "3", season: "Open all year" },
            { name: "Bull Shark", minSize: 0, maxSize: null, bagLimit: "3 (combined sharks and rays limit)", possessionLimit: "3", season: "Max size 700mm interdorsal length in West and South Coast bioregions" },
            { name: "Bronze Whaler Shark", minSize: 0, maxSize: null, bagLimit: "3 (combined sharks and rays limit)", possessionLimit: "3", season: "Max size 700mm interdorsal length in West and South Coast bioregions" },
            { name: "Dusky Shark", minSize: 0, maxSize: null, bagLimit: "3 (combined sharks and rays limit)", possessionLimit: "3", season: "Max size 700mm interdorsal length in West and South Coast bioregions" },
            { name: "Sandbar Shark", minSize: 0, maxSize: null, bagLimit: "3 (combined sharks and rays limit)", possessionLimit: "3", season: "Open all year" },
            { name: "Whale Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected Ningaloo filter-feeding giant. Total prohibition" },
            { name: "Great White Shark (White Pointer)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected apex predator. Total prohibition" },
            { name: "Grey Nurse Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered shark. Total prohibition" },
            { name: "Speartooth Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered riverine shark. Total prohibition" },
            { name: "Sawfish (Freshwater Sawfish)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "All sawfish species protected. Total prohibition" },
            { name: "Potato Rockcod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected reef groper. Total prohibition" },
            { name: "Queensland Groper", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected giant groper. Total prohibition" },
            { name: "Humphead Maori Wrasse", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected coral reef wrasse. Total prohibition" }
        ]
    },
    SA: {
        stateName: "South Australia",
        freshwater: [
            { name: "Murray Cod", minSize: 55, maxSize: 75, bagLimit: "1 (boat limit 2)", possessionLimit: "2", season: "Closed Aug 1 - Dec 31 in River Murray. Slot limit 55-75cm (Catch & release allowed in designated areas)" },
            { name: "Golden Perch", minSize: 33, maxSize: null, bagLimit: "5 (boat limit 15)", possessionLimit: "10", season: "Open all year" },
            { name: "Freshwater Catfish (Eel-tailed Catfish / Murray River Catfish)", minSize: "Protected in River Murray", maxSize: "N/A", bagLimit: "0 (River Murray), 2 (Stocked dams)", possessionLimit: "2", season: "Protected in River Murray. Permitted in stocked private waters" },
            { name: "Silver Perch", minSize: "Protected in Rivers", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected in all SA rivers & natural waterways. Return unharmed" },
            { name: "Trout Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered native species. Total prohibition on taking" },
            { name: "Brown Trout", minSize: 28, maxSize: null, bagLimit: "5 (boat limit 15)", possessionLimit: "10", season: "Open all year" },
            { name: "Rainbow Trout", minSize: 28, maxSize: null, bagLimit: "5 (boat limit 15)", possessionLimit: "10", season: "Open all year" },
            { name: "Redfin Perch", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Controlled pest species. Do not return to water alive" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Noxious pest species. Do not return to water alive" }
        ],
        saltwater: [
            { name: "King George Whiting", minSize: 32, maxSize: null, bagLimit: "10 (boat limit 30)", possessionLimit: "20", season: "Min 32cm in Gulf St Vincent & Spencer Gulf (30cm in West Coast & South East). Daily bag 10 (12 on West Coast)" },
            { name: "Pink Snapper", minSize: 38, maxSize: null, bagLimit: "0 (Closed in GSV, Spencer Gulf & West Coast)", possessionLimit: "0", season: "Closed in Gulf St Vincent, Spencer Gulf & West Coast until stock recovery. South East open: tag system / bag limit 1" },
            { name: "Southern Garfish", minSize: 23, maxSize: null, bagLimit: "20 (boat limit 60)", possessionLimit: "40", season: "Closed periods apply in northern Gulf St Vincent & Spencer Gulf" },
            { name: "Yellowfin Whiting", minSize: 24, maxSize: null, bagLimit: "20 (boat limit 60)", possessionLimit: "40", season: "Open all year" },
            { name: "Sand Flathead", minSize: 30, maxSize: null, bagLimit: "10 (boat limit 30)", possessionLimit: "20", season: "Open all year (Combined flathead limit)" },
            { name: "Flounder", minSize: 21, maxSize: null, bagLimit: "20 (boat limit 60)", possessionLimit: "40", season: "Open all year" },
            { name: "Western Australian Salmon", minSize: 21, maxSize: null, bagLimit: "20 (under 35cm) or 10 (over 35cm; boat limit 30)", possessionLimit: "40", season: "Open all year" },
            { name: "Australian Herring (Tommy Ruff)", minSize: 0, maxSize: null, bagLimit: "40 (boat limit 120)", possessionLimit: "80", season: "Open all year" },
            { name: "Black Bream", minSize: 28, maxSize: null, bagLimit: "10 (boat limit 30; Coorong bag 5)", possessionLimit: "20", season: "Open all year" },
            { name: "Mulloway", minSize: 82, maxSize: null, bagLimit: "2 (Lakes & Coorong), 5 (elsewhere with max 2 over 75cm)", possessionLimit: "10", season: "Min 82cm in Coorong; Min 46cm elsewhere. Boat limit 6 (Coorong)" },
            { name: "Snook", minSize: 45, maxSize: null, bagLimit: "20 (boat limit 60)", possessionLimit: "40", season: "Open all year" },
            { name: "Silver Trevally", minSize: 24, maxSize: null, bagLimit: "20 (boat limit 60)", possessionLimit: "40", season: "Open all year" },
            { name: "Yellowtail Kingfish", minSize: 60, maxSize: null, bagLimit: "1 (boat limit 3)", possessionLimit: "2", season: "Open all year (Upper Spencer Gulf spawning closure applies)" },
            { name: "Samsonfish", minSize: 60, maxSize: null, bagLimit: "1 (boat limit 3)", possessionLimit: "2", season: "Open all year" },
            { name: "Western Blue Groper", minSize: 60, maxSize: 100, bagLimit: "1 (boat limit 3)", possessionLimit: "1", season: "Slot limit 60-100cm. Closed in Gulf St Vincent, Spencer Gulf & Investigator Strait" },
            { name: "Blue Morwong (Queen Snapper)", minSize: 38, maxSize: null, bagLimit: "5 (boat limit 15)", possessionLimit: "10", season: "Open all year" },
            { name: "Bight Redfish", minSize: 30, maxSize: null, bagLimit: "10 (boat limit 30)", possessionLimit: "20", season: "Open all year (Red Snapper / Nannygai)" },
            { name: "Blue-eye Trevalla", minSize: 0, maxSize: null, bagLimit: "5 (boat limit 15)", possessionLimit: "10", season: "Open all year" },
            { name: "Southern Bluefin Tuna", minSize: 0, maxSize: null, bagLimit: "2 (boat limit 6)", possessionLimit: "2", season: "Open all year" },
            { name: "Albacore Tuna", minSize: 0, maxSize: null, bagLimit: "5 (boat limit 15)", possessionLimit: "10", season: "Open all year" },
            { name: "Skipjack Tuna", minSize: 0, maxSize: null, bagLimit: "5 (boat limit 15)", possessionLimit: "10", season: "Open all year" },
            { name: "Gummy Shark", minSize: 45, maxSize: null, bagLimit: "2 (Spencer Gulf), 1 (GSV & elsewhere; boat limit 6/3)", possessionLimit: "2", season: "Min 45cm 5th gill slit to tail base (or 75cm total length). Combined shark limit" },
            { name: "School Shark", minSize: 45, maxSize: null, bagLimit: "1 (boat limit 3)", possessionLimit: "1", season: "Min 45cm 5th gill slit to tail base (or 75cm total length). Combined shark limit" },
            { name: "Bronze Whaler Shark", minSize: 0, maxSize: null, bagLimit: "1 (boat limit 3)", possessionLimit: "1", season: "Open all year (Combined whaler shark limit)" },
            { name: "Broadnose Sevengill Shark (Seven-gill Shark)", minSize: 0, maxSize: null, bagLimit: "1 (boat limit 3)", possessionLimit: "1", season: "Open all year" },
            { name: "Elephant Fish", minSize: 0, maxSize: null, bagLimit: "1 (boat limit 3)", possessionLimit: "1", season: "Open all year" },
            { name: "Great White Shark (White Pointer)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected apex predator. Total prohibition in all SA waters" },
            { name: "Grey Nurse Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered shark. Total prohibition" }
        ]
    },
    TAS: {
        stateName: "Tasmania",
        freshwater: [
            { name: "Brown Trout", minSize: 22, maxSize: null, bagLimit: "5 (or 12 in Great Lake; Western Lakes max 2 over 50cm)", possessionLimit: "10", season: "Opens 1st Sat in August - Closes Sunday nearest 30 April (Rainbow waters close late May)" },
            { name: "Rainbow Trout", minSize: 22, maxSize: null, bagLimit: "5 (or 12 in Great Lake; Western Lakes max 2 over 50cm)", possessionLimit: "10", season: "Opens 1st Sat in August - Closes late May in designated rainbow waters" },
            { name: "Brook Trout", minSize: 30, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Opens 1st Sat in August - Closes Sunday nearest 30 April (Clarence Lagoon)" },
            { name: "Tiger Trout", minSize: 30, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open during IFS inland season (Pet Reservoir & stocked waters)" },
            { name: "Atlantic Salmon", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open during IFS inland angling season" },
            { name: "River Blackfish", minSize: 22, maxSize: null, bagLimit: "12", possessionLimit: "24", season: "Open all year in inland waters" },
            { name: "Short-finned Eel", minSize: 30, maxSize: null, bagLimit: "12 (max 10kg)", possessionLimit: "24", season: "Open all year (Combined eel limit)" },
            { name: "Long-finned Eel", minSize: 30, maxSize: null, bagLimit: "12 (max 10kg)", possessionLimit: "24", season: "Open all year (Combined eel limit)" },
            { name: "Australian Grayling", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected endangered native fish. Total prohibition in all Tasmanian waters" },
            { name: "Redfin Perch", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Controlled pest species. Do not return to water alive" },
            { name: "Tench", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Controlled pest species. Humane dispatch recommended" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Noxious pest. Report sightings immediately to IFS" }
        ],
        saltwater: [
            { name: "Sand Flathead", minSize: 35, maxSize: null, bagLimit: "2 (Eastern & South-Eastern Zone), 5 (Northern & Western Zone)", possessionLimit: "10", season: "Open all year (Must be landed whole or as fillets with frame intact)" },
            { name: "Tiger Flathead", minSize: 33, maxSize: null, bagLimit: "10 (combined)", possessionLimit: "20", season: "Open all year" },
            { name: "Bluespotted Flathead", minSize: 33, maxSize: null, bagLimit: "10 (combined)", possessionLimit: "20", season: "Open all year" },
            { name: "Striped Trumpeter", minSize: 55, maxSize: null, bagLimit: "4 (only 1 over 75cm; boat limit applies)", possessionLimit: "8", season: "Closed Sept 1 - Oct 31 statewide" },
            { name: "Bastard Trumpeter", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Banded Morwong", minSize: 36, maxSize: 46, bagLimit: "2", possessionLimit: "4", season: "Closed March 1 - April 30 (Slot limit 36-46cm fork length; all outside slot must be released)" },
            { name: "Jackass Morwong (Grey Morwong / Jackass Fish)", minSize: 25, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Blue Morwong (Rubberlip Morwong)", minSize: 25, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Longsnout Boarfish (Giant Boarfish)", minSize: 45, maxSize: null, bagLimit: "2 (combined boarfish)", possessionLimit: "4", season: "Open all year" },
            { name: "Black Bream", minSize: 25, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Australian Salmon", minSize: 20, maxSize: null, bagLimit: "15 (only 5 over 35cm in shark refuge areas)", possessionLimit: "30", season: "Open all year (Combined with Australian Herring)" },
            { name: "Australian Herring (Tommy Ruff)", minSize: 20, maxSize: null, bagLimit: "15", possessionLimit: "30", season: "Open all year (Combined with Australian Salmon)" },
            { name: "Silver Trevally", minSize: 20, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Yellowtail Kingfish", minSize: 45, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year" },
            { name: "King George Whiting", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Sea Garfish", minSize: 25, maxSize: null, bagLimit: "15", possessionLimit: "30", season: "Closed mid-Nov to mid-Dec in northern/eastern waters (Measured from upper jaw)" },
            { name: "Flounder (Greenback & Longsnout Flounder)", minSize: 25, maxSize: null, bagLimit: "15", possessionLimit: "30", season: "Open all year" },
            { name: "Luderick (Blackfish)", minSize: 25, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Tailor", minSize: 25, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Blue Warehou", minSize: 25, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Barracouta (Snoek)", minSize: 0, maxSize: null, bagLimit: "15", possessionLimit: "30", season: "Open all year" },
            { name: "Snook (Pike)", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Yellow-eye Mullet", minSize: 0, maxSize: null, bagLimit: "15", possessionLimit: "30", season: "Open all year" },
            { name: "Sea Mullet (Bully Mullet)", minSize: 0, maxSize: null, bagLimit: "15", possessionLimit: "30", season: "Open all year" },
            { name: "Blue-throated Wrasse", minSize: 30, maxSize: null, bagLimit: "5 (combined all wrasse)", possessionLimit: "10", season: "Open all year" },
            { name: "Snapper (Pink Snapper)", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Mulloway", minSize: 60, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year" },
            { name: "Leatherjacket (all species)", minSize: 0, maxSize: null, bagLimit: "15", possessionLimit: "30", season: "Open all year" },
            { name: "Silver Sweep", minSize: 0, maxSize: null, bagLimit: "15", possessionLimit: "30", season: "Open all year" },
            { name: "Red Gurnard", minSize: 0, maxSize: null, bagLimit: "15", possessionLimit: "30", season: "Open all year" },
            { name: "Blue-eye Trevalla", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Hapuku", minSize: 0, maxSize: null, bagLimit: "5 (combined deep sea trevalla/groper limit)", possessionLimit: "10", season: "Open all year" },
            { name: "Bass Groper", minSize: 0, maxSize: null, bagLimit: "5 (combined deep sea trevalla/groper limit)", possessionLimit: "10", season: "Open all year" },
            { name: "Pink Ling", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Gemfish", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Jack Mackerel", minSize: 0, maxSize: null, bagLimit: "30", possessionLimit: "60", season: "Open all year" },
            { name: "Slimy Mackerel (Pacific Mackerel)", minSize: 0, maxSize: null, bagLimit: "30", possessionLimit: "60", season: "Open all year" },
            { name: "Australian Pilchard (Sardine)", minSize: 0, maxSize: null, bagLimit: "50 (combined baitfish)", possessionLimit: "100", season: "Open all year" },
            { name: "Australian Anchovy", minSize: 0, maxSize: null, bagLimit: "50 (combined baitfish)", possessionLimit: "100", season: "Open all year" },
            { name: "Southern Bluefin Tuna", minSize: 0, maxSize: null, bagLimit: "1 (boat limit 2)", possessionLimit: "2", season: "Open all year" },
            { name: "Yellowfin Tuna", minSize: 0, maxSize: null, bagLimit: "1 (boat limit 2)", possessionLimit: "2", season: "Open all year" },
            { name: "Bigeye Tuna", minSize: 0, maxSize: null, bagLimit: "1 (boat limit 2)", possessionLimit: "2", season: "Open all year" },
            { name: "Albacore Tuna", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year (Combined with Skipjack)" },
            { name: "Skipjack Tuna", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year (Combined with Albacore)" },
            { name: "Gummy Shark", minSize: 45, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Carcass length 45cm / total length 75cm (Combined gummy & school shark limit 2; max 1 school shark). Closed in Shark Refuge Areas" },
            { name: "School Shark", minSize: 45, maxSize: null, bagLimit: "1", possessionLimit: "2", season: "Carcass length 45cm / total length 75cm (Max 1 school shark). Closed in Shark Refuge Areas" },
            { name: "Elephant Fish", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year (Closed in Shark Refuge Areas)" },
            { name: "Broadnose Sevengill Shark (Seven-gill Shark)", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Common Sawshark (Sawshark)", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year" },
            { name: "Mako Shark", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Great White Shark (White Pointer)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected apex predator. Total prohibition in all Tasmanian waters" },
            { name: "Grey Nurse Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered shark. Total prohibition" }
        ]
    },
    NT: {
        stateName: "Northern Territory",
        freshwater: [
            { name: "Barramundi", minSize: 55, maxSize: null, bagLimit: "5 (NT-wide), 3 (Kakadu / Mary / Daly River)", possessionLimit: "5 (or 3 in Fish Management Zones)", season: "Daly River seasonal closure Oct 1 - Jan 31. Kakadu, Mary & Daly River max size 90cm (vessel limit 1 over 90cm)" },
            { name: "Saratoga (Northern Saratoga)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Within 15 fish General Personal Possession Limit)" },
            { name: "Sooty Grunter", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Within 15 fish General Personal Possession Limit)" },
            { name: "Australian Grayling", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected native freshwater fish" }
        ],
        saltwater: [
            { name: "Barramundi", minSize: 55, maxSize: null, bagLimit: "5 (NT-wide), 3 (Kakadu / Mary / Daly River)", possessionLimit: "5 (or 3 in Fish Management Zones)", season: "NT-wide min size 55cm (fillet min 27cm). Kakadu, Mary & Daly River max size 90cm (vessel limit 1 over 90cm). Daly River closed Oct 1 - Jan 31" },
            { name: "Golden Snapper (Fingermark)", minSize: 0, maxSize: null, bagLimit: "3", possessionLimit: "3", season: "At-risk species (susceptible to barotrauma; vessel limits apply)" },
            { name: "Black Jewfish", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "At-risk species (susceptible to barotrauma; vessel limits apply)" },
            { name: "King Threadfin", minSize: 0, maxSize: null, bagLimit: "3", possessionLimit: "3", season: "Kakadu, Mary & Daly River max size 90cm fork length (vessel limit 1 over 90cm)" },
            { name: "Blue Threadfin", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Within 15 fish General Personal Possession Limit)" },
            { name: "Mangrove Jack", minSize: 35, maxSize: null, bagLimit: "3", possessionLimit: "3", season: "At-risk species (vessel limits apply)" },
            { name: "Spanish Mackerel", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Sensitive to handling; barbless hooks recommended for catch and release" },
            { name: "Crimson Snapper (Small-mouth Nannygai)", minSize: 0, maxSize: null, bagLimit: "10 (combined red snappers)", possessionLimit: "10", season: "Combined limit with Saddletail and Indonesian Snapper" },
            { name: "Saddletail Snapper (Large-mouth Nannygai)", minSize: 0, maxSize: null, bagLimit: "10 (combined red snappers)", possessionLimit: "10", season: "Combined limit with Crimson and Indonesian Snapper" },
            { name: "Grass Emperor (Tricky Snapper)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "At-risk species (susceptible to barotrauma; vessel limits apply)" },
            { name: "Stripey Snapper (Spanish Flag)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "At-risk species (susceptible to barotrauma; vessel limits apply)" },
            { name: "Russell's Snapper (Moses Snapper)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "At-risk species (susceptible to barotrauma; vessel limits apply)" },
            { name: "Blackspot Tuskfish", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "At-risk species (susceptible to barotrauma; vessel limits apply)" },
            { name: "Coral Trout", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "At-risk species (susceptible to barotrauma; vessel limits apply)" },
            { name: "Red Emperor", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "At-risk species (susceptible to barotrauma; vessel limits apply)" },
            { name: "Goldspotted Rockcod (Estuary Cod)", minSize: 0, maxSize: 120, bagLimit: "5", possessionLimit: "5", season: "Max length 120cm (all cod/groper > 1.2m protected; vessel limits apply)" },
            { name: "Rankin Cod", minSize: 0, maxSize: 120, bagLimit: "5", possessionLimit: "5", season: "Max length 120cm (all cod/groper > 1.2m protected; vessel limits apply)" },
            { name: "Barramundi Cod", minSize: 0, maxSize: 120, bagLimit: "5", possessionLimit: "5", season: "Max length 120cm (all cod/groper > 1.2m protected; vessel limits apply)" },
            { name: "Black Bream", minSize: 0, maxSize: null, bagLimit: "15", possessionLimit: "15", season: "Open all year (Acanthopagrus spp. bream limit 15)" },
            { name: "Blue Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year (Marlin and sailfish combined limit 1)" },
            { name: "Black Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year (Marlin and sailfish combined limit 1)" },
            { name: "Sailfish", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year (Marlin and sailfish combined limit 1)" },
            { name: "Giant Trevally", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Within 15 fish General Personal Possession Limit)" },
            { name: "Golden Trevally", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Within 15 fish General Personal Possession Limit)" },
            { name: "Queenfish", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Within 15 fish General Personal Possession Limit)" },
            { name: "Cobia", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Within 15 fish General Personal Possession Limit)" },
            { name: "Mahi Mahi (Dorado)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Within 15 fish General Personal Possession Limit)" },
            { name: "Tripletail", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Within 15 fish General Personal Possession Limit)" },
            { name: "Longtail Tuna (Northern Bluefin)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Within 15 fish General Personal Possession Limit)" },
            { name: "Mackerel Tuna (Little Tunny)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Within 15 fish General Personal Possession Limit)" },
            { name: "Yellowfin Tuna", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Within 15 fish General Personal Possession Limit)" },
            { name: "Yellowfin Whiting", minSize: 0, maxSize: null, bagLimit: "50 (combined)", possessionLimit: "50", season: "Combined whiting, mullet, garfish limit (Exempt from 15 GPL)" },
            { name: "Sea Garfish", minSize: 0, maxSize: null, bagLimit: "50 (combined)", possessionLimit: "50", season: "Combined whiting, mullet, garfish limit (Exempt from 15 GPL)" },
            { name: "Yellow-eye Mullet", minSize: 0, maxSize: null, bagLimit: "50 (combined)", possessionLimit: "50", season: "Combined whiting, mullet, garfish limit (Exempt from 15 GPL)" },
            { name: "Bull Shark", minSize: 0, maxSize: null, bagLimit: "3 (combined sharks)", possessionLimit: "3", season: "Open all year (Sharks combined limit 3)" },
            { name: "Bronze Whaler Shark", minSize: 0, maxSize: null, bagLimit: "3 (combined sharks)", possessionLimit: "3", season: "Open all year (Sharks combined limit 3)" },
            { name: "Northern River Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered river shark. Total prohibition" },
            { name: "Speartooth Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered river shark. Total prohibition" },
            { name: "Sawfish (Freshwater Sawfish)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "All 4 NT sawfish species protected (Narrow, Largetooth, Dwarf, Green). Total prohibition" },
            { name: "Queensland Groper", minSize: "Protected (>1.2m)", maxSize: "120cm", bagLimit: "0", possessionLimit: "0", season: "Protected giant reef groper. Total prohibition on taking any cod/groper over 1.2m" },
            { name: "Potato Rockcod", minSize: "Protected (>1.2m)", maxSize: "120cm", bagLimit: "0", possessionLimit: "0", season: "Protected giant reef groper. Total prohibition on taking any cod/groper over 1.2m" }
        ]
    },
    ACT: {
        stateName: "Australian Capital Territory",
        freshwater: [
            { name: "Murray Cod", minSize: 55, maxSize: 75, bagLimit: "1 (Murrumbidgee River), 2 (other waters)", possessionLimit: "2", season: "Open Dec 1 - Aug 31 (Closed Sept 1 - Nov 30). Murrumbidgee River downstream of Uriarra Crossing is Catch-and-Release only (Bag limit 0)" },
            { name: "Golden Perch", minSize: 30, maxSize: null, bagLimit: "2 (Murrumbidgee River), 5 (other waters)", possessionLimit: "10", season: "Open all year" },
            { name: "Brown Trout", minSize: 25, maxSize: null, bagLimit: "5 (combined trout)", possessionLimit: "10", season: "Trout Waters open October Labour Day weekend to June King's Birthday weekend (Open all year in Open Waters)" },
            { name: "Rainbow Trout", minSize: 25, maxSize: null, bagLimit: "5 (combined trout)", possessionLimit: "10", season: "Trout Waters open October Labour Day weekend to June King's Birthday weekend (Open all year in Open Waters)" },
            { name: "Australian Bass", minSize: 25, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year in stocked lakes and ponds" },
            { name: "Two-spined Blackfish", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Totally Protected native species (Ngunnawal: Wagar). Return to water immediately" },
            { name: "Macquarie Perch", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Totally Protected threatened species (Ngunnawal: Gubay). Return to water immediately" },
            { name: "Silver Perch", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Totally Protected native species in all ACT public waters & rivers (Ngunnawal: Dhingur)" },
            { name: "Trout Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Totally Protected endangered species (Ngunnawal: Gudu). Return to water immediately" },
            { name: "Redfin Perch", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Pest species. Anglers encouraged to humanely dispatch and not return to water" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Pest species. Anglers encouraged to humanely dispatch and not return to water" }
        ],
        saltwater: []
    }
};

window.REGULATIONS = REGULATIONS;
