// regulations.js - Australian Fish Size and Bag Regulations (Aligned with Official DPI/VFA/PIRSA/DPIRD Guidelines)

const REGULATIONS = {
    NSW: {
        stateName: "New South Wales",
        freshwater: [
            { name: "Murray Cod", minSize: 55, maxSize: 75, bagLimit: "2 (only 1 in rivers)", possessionLimit: "4", season: "Closed Sept 1 - Nov 30 (except Copeton & Blowering Dams)" },
            { name: "Golden Perch (Yellowbelly)", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Rainbow Trout", minSize: 25, maxSize: null, bagLimit: "5 (dams/lakes), 2 (streams)", possessionLimit: "10", season: "Streams closed June long weekend - Oct long weekend" },
            { name: "Brown Trout", minSize: 25, maxSize: null, bagLimit: "5 (dams/lakes), 2 (streams)", possessionLimit: "10", season: "Streams closed June long weekend - Oct long weekend" },
            { name: "Brook Trout", minSize: 25, maxSize: null, bagLimit: "5 (dams/lakes), 2 (streams)", possessionLimit: "10", season: "Streams closed June long weekend - Oct long weekend" },
            { name: "Atlantic Salmon", minSize: 25, maxSize: null, bagLimit: "5 (dams/lakes), 2 (streams)", possessionLimit: "10", season: "Streams closed June long weekend - Oct long weekend" },
            { name: "Australian Bass", minSize: 0, maxSize: null, bagLimit: "2 (combined with Estuary Perch; only 1 > 35cm in rivers)", possessionLimit: "4", season: "Rivers closed May 1 - Aug 31 (Catch & release permitted)" },
            { name: "Estuary Perch", minSize: 0, maxSize: null, bagLimit: "2 (combined with Bass; only 1 > 35cm in rivers)", possessionLimit: "4", season: "Rivers closed May 1 - Aug 31 (Catch & release permitted)" },
            { name: "Silver Perch", minSize: 25, maxSize: null, bagLimit: "5 (Listed dams only)", possessionLimit: "10", season: "Protected in all rivers (0 bag limit in all rivers)" },
            { name: "Freshwater Catfish (Eel-tailed Catfish)", minSize: 30, maxSize: null, bagLimit: "2 (Listed dams/eastern drainages only)", possessionLimit: "4", season: "Protected / 0 bag limit in western Murray-Darling rivers" },
            { name: "River Blackfish", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Check local river closures & regulations" },
            { name: "Two-spined Blackfish", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "High country alpine streams" },
            { name: "Spangled Perch", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Bony Bream (Pyramid Bream)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Long-finned Eel", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Short-finned Eel", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Macquarie Perch", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered native fish. Total no-take closure in all NSW waters" },
            { name: "Trout Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered native fish. Total closure, return to water immediately" },
            { name: "Eastern Freshwater Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered native fish. Total closure in northern coastal rivers" },
            { name: "Southern Purple-Spotted Gudgeon", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered native fish. Total closure" },
            { name: "Olive Perchlet", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered native fish. Total closure" },
            { name: "Southern Pygmy Perch", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Threatened native fish. Total closure" },
            { name: "Murray Hardyhead", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered native fish. Total closure" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared noxious pest. Illegal to return to water alive" },
            { name: "Redfin Perch", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared pest. Do not return to water alive" },
            { name: "Eastern Mosquitofish (Gambusia)", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared noxious pest" },
            { name: "Goldfish", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared non-native pest" },
            { name: "Oriental Weatherloach", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared noxious pest" }
        ],
        saltwater: [
            { name: "Dusky Flathead", minSize: 36, maxSize: 70, bagLimit: "5", possessionLimit: "10", season: "Open all year (Slot limit 36–70cm, all > 70cm must be released)" },
            { name: "Sand Flathead", minSize: 33, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year (Combined with Tiger Flathead)" },
            { name: "Tiger Flathead", minSize: 33, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Bluespotted Flathead", minSize: 33, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Yellowfin Bream", minSize: 25, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year (Combined with Black Bream & Tarwhine)" },
            { name: "Black Bream", minSize: 25, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Tarwhine", minSize: 20, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Snapper", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year (Only 1 > 70cm recommended)" },
            { name: "Sand Whiting", minSize: 27, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Trumpeter Whiting (Winter Whiting)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "King George Whiting", minSize: 32, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Mulloway", minSize: 70, maxSize: null, bagLimit: "1", possessionLimit: "2", season: "Open all year (Boat limit of 2 applied)" },
            { name: "Teraglin", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Yellowtail Kingfish", minSize: 65, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Samsonfish", minSize: 65, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Combined with Kingfish & Amberjack)" },
            { name: "Amberjack", minSize: 65, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Australian Salmon", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year (No min size limit)" },
            { name: "Tailor", minSize: 30, maxSize: null, bagLimit: "10 (only 5 over 35cm)", possessionLimit: "20", season: "Open all year" },
            { name: "Luderick (Blackfish)", minSize: 27, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Rock Blackfish (Black Drummer)", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Silver Drummer", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Silver Trevally", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Giant Trevally (GT)", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Bigeye Trevally", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Golden Trevally", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Mangrove Jack", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Mahi Mahi (Dorado)", minSize: 60, maxSize: null, bagLimit: "10 (only 1 over 110cm)", possessionLimit: "20", season: "Open all year" },
            { name: "Spanish Mackerel", minSize: 75, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Spotted Mackerel", minSize: 60, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "School Mackerel", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Wahoo", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Cobia (Black Kingfish)", minSize: 65, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Yellowfin Tuna", minSize: 90, maxSize: null, bagLimit: "5 (max 2 over 90cm across all large tuna combined)", possessionLimit: "5", season: "Open all year" },
            { name: "Southern Bluefin Tuna", minSize: 90, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year (Max 1 fish total)" },
            { name: "Bigeye Tuna", minSize: 90, maxSize: null, bagLimit: "5 (max 2 over 90cm combined)", possessionLimit: "5", season: "Open all year" },
            { name: "Albacore Tuna", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Longtail Tuna (Northern Bluefin)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Skipjack Tuna (Striped Tuna)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Mackerel Tuna (Little Tunny)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Australian Bonito", minSize: 0, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Striped Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Blue Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Black Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Sailfish", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Broadbill Swordfish", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Shortbill Spearfish", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Eastern Blue Groper", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Official NSW State Fish. Complete prohibition on line fishing & spearfishing" },
            { name: "Blue Morwong (Rubberlip Morwong)", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Grey Morwong (Jackass Fish)", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Red Morwong", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Pearl Perch", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Moses Snapper (Moses Perch)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Golden Snapper (Fingermark)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Bar Cod (Band-ed Rockcod)", minSize: 0, maxSize: null, bagLimit: "5 (combined deep sea)", possessionLimit: "5", season: "Open all year" },
            { name: "Bass Groper", minSize: 0, maxSize: null, bagLimit: "5 (combined deep sea)", possessionLimit: "5", season: "Open all year" },
            { name: "Hapuku", minSize: 0, maxSize: null, bagLimit: "5 (combined deep sea)", possessionLimit: "5", season: "Open all year" },
            { name: "Blue-eye Trevalla", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Gemfish", minSize: 0, maxSize: null, bagLimit: "5 (boat limit 10)", possessionLimit: "5", season: "Open all year" },
            { name: "Sea Garfish (Eastern Sea Garfish)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "River Garfish", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Yellowtail Scad (Yakker)", minSize: 0, maxSize: null, bagLimit: "50", possessionLimit: "50", season: "Open all year" },
            { name: "Slimy Mackerel (Pacific Mackerel)", minSize: 0, maxSize: null, bagLimit: "50", possessionLimit: "50", season: "Open all year" },
            { name: "Yellowfin Leatherjacket", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Six-spined Leatherjacket", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Flounder (Greenback & Small-toothed)", minSize: 25, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Sole (Black Sole / Many-banded Sole)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "John Dory", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Mirror Dory", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Silver Sweep", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Red Gurnard", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Sea Mullet (Bully Mullet)", minSize: 30, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Flat-tail Mullet / Sand Mullet", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Sergeant Baker", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Coral Trout (Bar-cheek & Leopard)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Gummy Shark", minSize: 0, maxSize: null, bagLimit: "5 (combined shark limit)", possessionLimit: "5", season: "Open all year" },
            { name: "School Shark", minSize: 91, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Mako Shark", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Tiger Shark", minSize: 0, maxSize: null, bagLimit: "1 (only 1 > 1.5m)", possessionLimit: "1", season: "Open all year" },
            { name: "Hammerhead Shark (Smooth)", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Great White Shark (White Pointer)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically protected. Total prohibition on taking or harming" },
            { name: "Grey Nurse Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered. Total prohibition" },
            { name: "Scalloped Hammerhead Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered. Total prohibition" },
            { name: "Great Hammerhead Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Endangered. Total prohibition" },
            { name: "Black Rockcod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected marine fish. Total prohibition in all NSW waters" },
            { name: "Ballina Angelfish", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected marine fish. Total prohibition" }
        ]
    },
    VIC: {
        stateName: "Victoria",
        freshwater: [
            { name: "Murray Cod", minSize: 55, maxSize: 75, bagLimit: "1 (Rivers), 2 (Lakes)", possessionLimit: "4", season: "Closed Sept 1 - Nov 30 (except Lake Eildon)" },
            { name: "Golden Perch", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Brown Trout", minSize: 0, maxSize: null, bagLimit: "5 (only 2 over 35cm in streams)", possessionLimit: "10", season: "Streams closed June 9 - Sept 4" },
            { name: "Rainbow Trout", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Streams closed June 9 - Sept 4" },
            { name: "Australian Bass", minSize: 27, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year" },
            { name: "Estuary Perch", minSize: 27, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Silver Perch", minSize: 30, maxSize: null, bagLimit: "5 (Stocked dams only)", possessionLimit: "10", season: "Rivers closed all year (protected)" },
            { name: "Trout Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected. Release immediately" },
            { name: "Macquarie Perch", minSize: "Protected (most areas)", maxSize: "N/A", bagLimit: "0 (except select dams)", possessionLimit: "0", season: "Check VFA regulations, closed in most rivers" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Pest species. Do not return to water alive" },
            { name: "Redfin Perch", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Open all year" }
        ],
        saltwater: [
            { name: "Dusky Flathead", minSize: 30, maxSize: 55, bagLimit: "5", possessionLimit: "10", season: "Open all year (slot limit 30-55cm)" },
            { name: "Sand Flathead", minSize: 27, maxSize: null, bagLimit: "20 (combined)", possessionLimit: "40", season: "Open all year" },
            { name: "Snapper", minSize: 28, maxSize: null, bagLimit: "10 (only 3 over 40cm)", possessionLimit: "20", season: "Open all year" },
            { name: "King George Whiting", minSize: 27, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Black Bream", minSize: 28, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Silver Trevally", minSize: 20, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Tailor", minSize: 23, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Mulloway", minSize: 60, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Luderick", minSize: 23, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Garfish", minSize: 0, maxSize: null, bagLimit: "40", possessionLimit: "80", season: "Open all year" }
        ]
    },
    QLD: {
        stateName: "Queensland",
        freshwater: [
            { name: "Barramundi", minSize: 58, maxSize: 120, bagLimit: "5", possessionLimit: "5", season: "Closed Nov 1 - Feb 1 (East Coast rivers); Oct 7 - Jan 31 (Gulf of Carpentaria)" },
            { name: "Golden Perch", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Murray Cod", minSize: 60, maxSize: 110, bagLimit: "2", possessionLimit: "2", season: "Closed Aug 1 - Oct 31 in QLD waters" },
            { name: "Sooty Grunter", minSize: 28, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Saratoga", minSize: 50, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Silver Perch", minSize: 30, maxSize: null, bagLimit: "5 (Stocked dams only)", possessionLimit: "5", season: "Protected / 0 bag in natural river drainages" },
            { name: "Freshwater Catfish (Eel-tailed Catfish)", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Mary River Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected endangered native. Total closure in Mary River system" },
            { name: "Speartooth Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered river shark. Total no-take closure" },
            { name: "Sawfish (Freshwater & Green)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered. Total no-take closure" },
            { name: "Tilapia", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared noxious pest. Euthanise humanely, do not release" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Declared pest. Illegal to return to water alive" }
        ],
        saltwater: [
            { name: "Barramundi", minSize: 58, maxSize: 120, bagLimit: "5", possessionLimit: "5", season: "East Coast closed Nov 1 - Feb 1; Gulf closed Oct 7 - Jan 31 (Slot limit 58-120cm)" },
            { name: "Black Jewfish", minSize: 75, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year (Closed periods apply by management zone once quota reached)" },
            { name: "Mulloway", minSize: 75, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Teraglin", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Snapper", minSize: 35, maxSize: null, bagLimit: "4 (only 1 over 70cm)", possessionLimit: "4", season: "Closed July 15 - Aug 15" },
            { name: "Pearl Perch", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Closed July 15 - Aug 15" },
            { name: "Dusky Flathead", minSize: 40, maxSize: 75, bagLimit: "5", possessionLimit: "5", season: "Open all year (Slot limit 40-75cm, all > 75cm must be released)" },
            { name: "Sand Flathead", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Yellowfin Bream", minSize: 25, maxSize: null, bagLimit: "30", possessionLimit: "30", season: "Open all year (Combined bream/tarwhine total 30)" },
            { name: "Black Bream", minSize: 25, maxSize: null, bagLimit: "30", possessionLimit: "30", season: "Open all year" },
            { name: "Pikey Bream", minSize: 25, maxSize: null, bagLimit: "30", possessionLimit: "30", season: "Open all year" },
            { name: "Tarwhine", minSize: 25, maxSize: null, bagLimit: "30", possessionLimit: "30", season: "Open all year" },
            { name: "Sand Whiting", minSize: 25, maxSize: null, bagLimit: "30", possessionLimit: "30", season: "Open all year (Combined whiting limit 30)" },
            { name: "Goldenline Whiting", minSize: 25, maxSize: null, bagLimit: "30", possessionLimit: "30", season: "Open all year" },
            { name: "Trumpeter Whiting (Winter Whiting)", minSize: 0, maxSize: null, bagLimit: "50", possessionLimit: "50", season: "Open all year" },
            { name: "Tailor", minSize: 35, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year (Fraser Island/K'gari closed Aug 1 - Sept 30)" },
            { name: "Mangrove Jack", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Red Emperor", minSize: 55, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Combined coral reef fin fish max 20)" },
            { name: "Crimson Seaperch (Small mouth Nannygai)", minSize: 40, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Combined coral reef fin fish)" },
            { name: "Saddletail Seaperch (Large mouth Nannygai)", minSize: 40, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Combined coral reef fin fish)" },
            { name: "Golden Snapper (Fingermark)", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Moses Snapper (Moses Perch)", minSize: 25, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Stripey Snapper (Spanish Flag)", minSize: 25, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Hussar", minSize: 25, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Coral Trout", minSize: 38, maxSize: null, bagLimit: "7", possessionLimit: "7", season: "Combined coral reef fin fish max 20; Coral reef fin fish closures apply in Oct/Nov" },
            { name: "Barramundi Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected coral reef species. Total no-take closure" },
            { name: "Queensland Groper (Giant Grouper)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected marine species. Total no-take closure" },
            { name: "Potato Rockcod (Potato Cod)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected reef cod. Total no-take closure" },
            { name: "Humphead Maori Wrasse", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected coral reef wrasse. Total no-take closure" },
            { name: "Estuary Cod (Goldspotted & Blackspotted Rockcod)", minSize: 38, maxSize: 100, bagLimit: "5", possessionLimit: "5", season: "Open all year (Slot limit 38-100cm; combined cod/grouper limit)" },
            { name: "Coral Rockcod", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Maori Rockcod", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Flowery Cod", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Spanish Mackerel", minSize: 75, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Northern closure (Oct-Nov) & Southern closure (Feb-Mar) apply" },
            { name: "Spotted Mackerel", minSize: 60, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "School Mackerel", minSize: 50, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Grey Mackerel (Broadbarred)", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Shark Mackerel", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Wahoo", minSize: 75, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Cobia (Black Kingfish)", minSize: 75, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Yellowtail Kingfish", minSize: 60, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Samsonfish", minSize: 50, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Amberjack", minSize: 50, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Giant Trevally (GT)", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Combined trevally possession limit 5)" },
            { name: "Bigeye Trevally", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Golden Trevally", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Queenfish", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Mahi Mahi (Dorado)", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Yellowfin Tuna", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year (Combined tuna possession limit 5)" },
            { name: "Longtail Tuna (Northern Bluefin)", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Mackerel Tuna (Little Tunny)", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Skipjack Tuna", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Albacore Tuna", minSize: 0, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Bigeye Tuna", minSize: 0, maxSize: null, bagLimit: "2", possessionLimit: "2", season: "Open all year" },
            { name: "Striped Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Blue Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Black Marlin", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Sailfish", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Broadbill Swordfish", minSize: 0, maxSize: null, bagLimit: "1", possessionLimit: "1", season: "Open all year" },
            { name: "Spangled Emperor", minSize: 45, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year (Combined emperor limit)" },
            { name: "Redthroat Emperor (Sweetlip)", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Grass Emperor (Sweetlip)", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Lancer (Redspot Emperor)", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Longnose Emperor", minSize: 38, maxSize: null, bagLimit: "5", possessionLimit: "5", season: "Open all year" },
            { name: "Luderick (Blackfish)", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "10", season: "Open all year" },
            { name: "Silver Trevally", minSize: 25, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Garfish", minSize: 0, maxSize: null, bagLimit: "50", possessionLimit: "50", season: "Open all year" },
            { name: "Yellowtail Scad (Yakker)", minSize: 0, maxSize: null, bagLimit: "50", possessionLimit: "50", season: "Open all year" },
            { name: "Slimy Mackerel (Pacific Mackerel)", minSize: 0, maxSize: null, bagLimit: "50", possessionLimit: "50", season: "Open all year" },
            { name: "Flounder (Greenback & Small-toothed)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "General tidal possession limit applies" },
            { name: "Sole (Black Sole / Many-banded Sole)", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "General tidal possession limit applies" },
            { name: "Sea Mullet (Bully Mullet)", minSize: 30, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year (Others no size limit)" },
            { name: "Flat-tail Mullet / Sand Mullet", minSize: 0, maxSize: null, bagLimit: "20", possessionLimit: "20", season: "Open all year" },
            { name: "Tiger Shark", minSize: 0, maxSize: 150, bagLimit: "1", possessionLimit: "1", season: "Max 1.5m length limit across all sharks; total shark limit 1" },
            { name: "Gummy Shark", minSize: 0, maxSize: 150, bagLimit: "1", possessionLimit: "1", season: "Max 1.5m length limit across all sharks; total shark limit 1" },
            { name: "Mako Shark", minSize: 0, maxSize: 150, bagLimit: "1", possessionLimit: "1", season: "Max 1.5m length limit across all sharks; total shark limit 1" },
            { name: "Great White Shark (White Pointer)", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected apex predator. Total no-take closure" },
            { name: "Grey Nurse Shark", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Critically endangered shark. Total no-take closure" }
        ]
    },
    WA: {
        stateName: "Western Australia",
        freshwater: [
            { name: "Rainbow Trout", minSize: 30, maxSize: null, bagLimit: "4", possessionLimit: "8", season: "Closed July 1 - Aug 31" },
            { name: "Brown Trout", minSize: 30, maxSize: null, bagLimit: "4", possessionLimit: "8", season: "Closed July 1 - Aug 31" },
            { name: "Redfin Perch", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Open all year" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Pest. Do not return to water alive" }
        ],
        saltwater: [
            { name: "Pink Snapper", minSize: 41, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Closed periods apply for Cockburn Sound & Shark Bay" },
            { name: "Barramundi", minSize: 55, maxSize: 80, bagLimit: "2", possessionLimit: "4", season: "Open all year (slot limit 55-80cm)" },
            { name: "King George Whiting", minSize: 28, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Tarwhine", minSize: 25, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Tailor", minSize: 30, maxSize: null, bagLimit: "8 (only 2 over 50cm)", possessionLimit: "16", season: "Open all year" },
            { name: "Black Bream", minSize: 25, maxSize: null, bagLimit: "6", possessionLimit: "12", season: "Open all year" },
            { name: "Flathead (Blue-spotted/Southern)", minSize: 30, maxSize: null, bagLimit: "8", possessionLimit: "16", season: "Open all year" },
            { name: "Giant Trevally", minSize: 35, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year" },
            { name: "Queenfish", minSize: 50, maxSize: null, bagLimit: "3", possessionLimit: "6", season: "Open all year" }
        ]
    },
    SA: {
        stateName: "South Australia",
        freshwater: [
            { name: "Murray Cod", minSize: 55, maxSize: 75, bagLimit: "1", possessionLimit: "2", season: "Closed Aug 1 - Dec 31 (Catch & Release permitted in some zones)" },
            { name: "Golden Perch", minSize: 33, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Brown Trout", minSize: 28, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Rainbow Trout", minSize: 28, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Trout Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected. Heavy penalties apply" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Pest. Do not release back into water" }
        ],
        saltwater: [
            { name: "Snapper", minSize: 38, maxSize: null, bagLimit: "0 (Spencer Gulf/GSV/West Coast closed)", possessionLimit: "0", season: "Strict fishery closures in place. South East zone open: limit 1" },
            { name: "King George Whiting", minSize: 32, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Garfish", minSize: 23, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Salmon (Western Australian)", minSize: 21, maxSize: null, bagLimit: "20 (only 5 over 35cm)", possessionLimit: "40", season: "Open all year" },
            { name: "Black Bream", minSize: 28, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Yellowfin Whiting", minSize: 24, maxSize: null, bagLimit: "20", possessionLimit: "40", season: "Open all year" },
            { name: "Sand Flathead", minSize: 30, maxSize: null, bagLimit: "10", possessionLimit: "20", season: "Open all year" },
            { name: "Mulloway", minSize: 82, maxSize: null, bagLimit: "2 (Coorong area), 5 (elsewhere)", possessionLimit: "10", season: "Open all year" }
        ]
    },
    TAS: {
        stateName: "Tasmania",
        freshwater: [
            { name: "Brown Trout", minSize: 22, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Streams closed May - Aug (check IFS regulations)" },
            { name: "Rainbow Trout", minSize: 22, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Streams closed May - Aug (check IFS regulations)" },
            { name: "Atlantic Salmon", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open during inland season" },
            { name: "Brook Trout", minSize: 22, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Streams closed May - Aug (check IFS)" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Pest. Report sightings immediately to IFS" }
        ],
        saltwater: [
            { name: "Sand Flathead", minSize: 32, maxSize: null, bagLimit: "10 (only 2 over 40cm)", possessionLimit: "20", season: "Open all year (Tiger/Dusky flathead 32cm limit)" },
            { name: "Striped Trumpeter", minSize: 45, maxSize: null, bagLimit: "4", possessionLimit: "8", season: "Closed Sept 1 - Oct 31" },
            { name: "Sea Garfish", minSize: 25, maxSize: null, bagLimit: "15", possessionLimit: "30", season: "Open all year" },
            { name: "Bream (Black)", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Australian Salmon", minSize: 20, maxSize: null, bagLimit: "15", possessionLimit: "30", season: "Open all year" },
            { name: "King George Whiting", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Silver Trevally", minSize: 22, maxSize: null, bagLimit: "15", possessionLimit: "30", season: "Open all year" }
        ]
    },
    NT: {
        stateName: "Northern Territory",
        freshwater: [
            { name: "Barramundi", minSize: 55, maxSize: null, bagLimit: "5 (only 1 over 90cm)", possessionLimit: "5", season: "Open all year (Regional management closures apply)" },
            { name: "Sooty Grunter", minSize: 25, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Saratoga", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" }
        ],
        saltwater: [
            { name: "Barramundi", minSize: 55, maxSize: null, bagLimit: "5 (only 1 over 90cm)", possessionLimit: "5", season: "Open all year" },
            { name: "Golden Snapper", minSize: 30, maxSize: null, bagLimit: "3", possessionLimit: "3", season: "Open all year" },
            { name: "Mangrove Jack", minSize: 35, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Spanish Mackerel", minSize: 75, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Giant Trevally", minSize: 0, maxSize: null, bagLimit: "3", possessionLimit: "6", season: "Open all year" },
            { name: "Queenfish", minSize: 50, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" }
        ]
    },
    ACT: {
        stateName: "Australian Capital Territory",
        freshwater: [
            { name: "Murray Cod", minSize: 55, maxSize: 75, bagLimit: "1", possessionLimit: "2", season: "Closed Sept 1 - Nov 30" },
            { name: "Golden Perch", minSize: 30, maxSize: null, bagLimit: "5", possessionLimit: "10", season: "Open all year" },
            { name: "Brown Trout", minSize: 25, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Closed June long weekend - Oct long weekend" },
            { name: "Rainbow Trout", minSize: 25, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Closed June long weekend - Oct long weekend" },
            { name: "Silver Perch", minSize: 30, maxSize: null, bagLimit: "5 (Stocked dams only)", possessionLimit: "10", season: "Protected in rivers (Illegal to take)" },
            { name: "Trout Cod", minSize: "Protected", maxSize: "N/A", bagLimit: "0", possessionLimit: "0", season: "Protected. Return to water immediately" },
            { name: "European Carp", minSize: "No Limit (Pest)", maxSize: "N/A", bagLimit: "Unlimited", possessionLimit: "Unlimited", season: "Pest. Do not return to water alive" },
            { name: "Australian Bass", minSize: 25, maxSize: null, bagLimit: "2", possessionLimit: "4", season: "Open all year" }
        ],
        saltwater: []
    }
};

window.REGULATIONS = REGULATIONS;
